In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
import numpy as np
import matplotlib.pyplot as plt

In [2]:
response = requests.get('https://www.tanea.gr/tag/%CF%85%CF%80%CE%BF%CE%BA%CE%BB%CE%BF%CF%80%CE%AD%CF%82/')
doc = BeautifulSoup(response.text, 'html.parser')

In [3]:
teaser_articles_list = []
for i in range(1, 37):
    # Construct the class string for the current iteration
    current_class_name = f'column is-full ro_{i}'

    # Find all divs with the constructed class name
    found_articles_for_i = doc.find_all('div', class_=current_class_name)

    if found_articles_for_i:
        # Add these articles to the main list
        teaser_articles_list.extend(found_articles_for_i)

        # Iterate through the articles found in this specific 'ro_i' class
        # and print their headlines
        for article_element in found_articles_for_i:
            headline_element = article_element.find('h3')
            if headline_element:
                print(headline_element.text.strip())
            else:
                print(f"No headline found for an article in '{current_class_name}'")
    else:
        print(f"No articles found for class '{current_class_name}' on this page.")

Απάντηση Τσουκαλά σε Φλωρίδη: Να ανασυρθεί από το αρχείο η υπόθεση των παράνομων υποκλοπών
Υποκλοπές: Νέα πολιτική θύελλα μετά τις αποκαλύψεις για συμφωνητικό με την ΕΥΠ
Μαξίμου για αίτημα ΠΑΣΟΚ να κληθεί στη Βουλή ο Ντίλιαν: «Θα αποφασίσουν τα αρμόδια όργανα»
Υποκλοπές: Ντόμινο εξελίξεων μετά τις δηλώσεις Ντίλιαν – Ο Κουκάκης ζητά ανάσυρση του φακέλου από το αρχείο
Υποκλοπές: Αίτημα του ΠΑΣΟΚ για ακρόαση στην Επιτροπή Θεσμών και Διαφάνειας των Ταλ Ντίλιαν και Γρηγόρη Δημητριάδη
ΕΛΑΣ για δηλώσεις Ντίλιαν: «Ο κ. Μητσοτάκης δεν μπορεί άλλο να κρύβεται – Να δώσει απαντήσεις και στοιχεία»
Υποκλοπές: Ντίλιαν καρφώνει κυβέρνηση – «Πουλάμε μόνο σε κρατικές αρχές, δεν λειτουργούμε τα συστήματα οι ίδιοι»
Κ. Τσουκαλάς: Δημοκρατικό καθήκον προς τους πολίτες η διαλεύκανση των παράνομων παρακολουθήσεων
Κεσσές για υποκλοπές: Σκυταλοδρομία συγκάλυψης – Προβληματική η ανάθεση της υπόθεσης από τον Τζαβέλλα στον Μπακέλα
Ηρεμα νερά
«Ypoklopes Blues»
Τσουκαλάς: A λα καρτ αντίληψη της εθνικής ασφάλειας από την κυβέρνηση – Να ζητήσει συγγνώμη από τον Ανδρουλάκη
Χάχανο
Κ. Τσουκαλάς: Ο κ. Φλωρίδης με περισπούδαστο ύφος απηύθυνε ειρωνείες περί “φωστήρων”, αλλά πιάστηκε αδιάβαστος
«Βόμβες» Σαμαρά για εθνικά και υποκλοπές: Η Ελλάδα έχει μετατραπεί σε ένα απέραντο φρενοκομείο
Υποκλοπές: Καταψηφίστηκε η πρόταση του ΠΑΣΟΚ για σύσταση Εξεταστικής Επιτροπής- «Βόμβες» Σαμαρά
Υποκλοπές: Στη Βουλή η κρίσιμη μάχη για την εξεταστική – Το Μαξίμου «δείχνει» εθνική ασφάλεια για την απόρριψη
Γκάλοπ
Υποκλοπές: Τι θα κάνει το Μαξίμου με την Εξεταστική – «Λίγη υπομονή…»
Ανδρουλάκης κατά Κακλαμάνη για τις υποκλοπές: «Α λα καρτ ευαισθησίες» – Κλιμακώνεται η πολιτική σύγκρουση
Υποκλοπές: Στην επιτροπή Δεοντολογίας στέλνει ο Κακλαμάνης το θέμα των διαρροών για ΕΥΠ
Δεν είναι αρκετό
Κυβερνητικές πηγές για διαρροή διαλόγου Ανδρουλάκη – Δεμίρη: Ο πρόεδρος του ΠΑΣΟΚ μετεξελίσσεται σε «πράσινη Ζωή»
Επιτροπή Θεσμών και Διαφάνειας: Αναβλήθηκε η συνεδρίαση για την ακρόαση του Κ. Τζαβέλλα μετά την επιστολή του
Υποκλοπές: «Η παρακολούθησή μου διατάχθηκε προφορικά;» – Έντονος διάλογος Ανδρουλάκη-Δεμίρη στην Επιτροπή
Υποκλοπές: Την Παρασκευή η συζήτηση στην ολομέλεια της πρότασης του ΠΑΣΟΚ για εξεταστική επιτροπή
Υποκλοπές: Στην Επιτροπή Θεσμών και Διαφάνειας ο Δεμίρης – «Όχι» από Τζαβέλλα
Νίκος Ανδρουλάκης: Παρών στην ακρόαση του διοικητή της ΕΥΠ, Θ. Δεμίρη, για τις υποκλοπές
Νέα Αριστερά: Ο κ. Τζαβέλλας οφείλει να προσέλθει στην Επιτροπή Θεσμών και Διαφάνειας και να δώσει απαντήσεις
ΠΑΣΟΚ για Τζαβέλλα: Η επίκληση της αρχής της διάκρισης των εξουσιών δεν πείθει κανέναν
Η Επιτροπή Θεσμών περιμένει αύριο Δεμίρη και Τζαβέλλα
«Όχι» Τζαβέλλα στην Επιτροπή Θεσμών για τις υποκλοπές – Επικαλείται διάκριση εξουσιών
Υποκλοπές: Την Τετάρτη στην Eπιτροπή Θεσμών και Διαφάνειας Δεμίρης και Τζαβέλλας
Συνέδριο σε ήρεμα νερά
Υποκλοπές: Επανέρχεται ο Χρήστος Σπίρτζης με ερωτήματα για την πορεία της δικογραφίας
Σκάνδαλο Υποκλοπών: Έρχονται 6 νέες μηνύσεις που «δείχνουν» κατασκοπεία

In [4]:
teaser_articles_list = []

start_page = 1
end_page = 7
base_tag_url = 'https://www.tanea.gr/tag/%CF%85%CF%80%CE%BF%CE%BA%CE%BB%CE%BF%CF%80%CE%AD%CF%82/'

for page_num in range(start_page, end_page + 1):
    print(f"--- Processing Page {page_num} ---")

    if page_num == 1:
        page_url = base_tag_url
    else:
        page_url = f"{base_tag_url}page/{page_num}/"

    try:
        response_page = requests.get(page_url)
        response_page.raise_for_status() # Raise an HTTPError for bad responses (4xx or 5xx)
        doc = BeautifulSoup(response_page.text, 'html.parser') # Update doc for each page
    except requests.exceptions.RequestException as e:
        print(f"Could not fetch page {page_url}: {e}")
        continue # Skip to the next page if page fetch fails

    for i in range(1, 37):
        # Construct the class string for the current iteration
        current_class_name = f'column is-full ro_{i}'

        # Find all divs with the constructed class name on the current page's doc
        found_articles_for_i = doc.find_all('div', class_=current_class_name)

        if found_articles_for_i:
            # Add these articles to the main list
            teaser_articles_list.extend(found_articles_for_i)

            # Iterate through the articles found in this specific 'ro_i' class
            # and print their headlines
            for article_element in found_articles_for_i:
                headline_element = article_element.find('h3')
                if headline_element:
                    print(headline_element.text.strip())
                else:
                    print(f"No headline found for an article in '{current_class_name}'")
        else:
            print(f"No articles found for class '{current_class_name}' on this page.")

--- Processing Page 1 ---
Απάντηση Τσουκαλά σε Φλωρίδη: Να ανασυρθεί από το αρχείο η υπόθεση των παράνομων υποκλοπών
Υποκλοπές: Νέα πολιτική θύελλα μετά τις αποκαλύψεις για συμφωνητικό με την ΕΥΠ
Μαξίμου για αίτημα ΠΑΣΟΚ να κληθεί στη Βουλή ο Ντίλιαν: «Θα αποφασίσουν τα αρμόδια όργανα»
Υποκλοπές: Ντόμινο εξελίξεων μετά τις δηλώσεις Ντίλιαν – Ο Κουκάκης ζητά ανάσυρση του φακέλου από το αρχείο
Υποκλοπές: Αίτημα του ΠΑΣΟΚ για ακρόαση στην Επιτροπή Θεσμών και Διαφάνειας των Ταλ Ντίλιαν και Γρηγόρη Δημητριάδη
ΕΛΑΣ για δηλώσεις Ντίλιαν: «Ο κ. Μητσοτάκης δεν μπορεί άλλο να κρύβεται – Να δώσει απαντήσεις και στοιχεία»
Υποκλοπές: Ντίλιαν καρφώνει κυβέρνηση – «Πουλάμε μόνο σε κρατικές αρχές, δεν λειτουργούμε τα συστήματα οι ίδιοι»
Κ. Τσουκαλάς: Δημοκρατικό καθήκον προς τους πολίτες η διαλεύκανση των παράνομων παρακολουθήσεων
Κεσσές για υποκλοπές: Σκυταλοδρομία συγκάλυψης – Προβληματική η ανάθεση της υπόθεσης από τον Τζαβέλλα στον Μπακέλα
Ηρεμα νερά
«Ypoklopes Blues»
Τσουκαλάς: A λα καρτ αντίληψη της εθνικής ασφάλειας από την κυβέρνηση – Να ζητήσει συγγνώμη από τον Ανδρουλάκη
Χάχανο
Κ. Τσουκαλάς: Ο κ. Φλωρίδης με περισπούδαστο ύφος απηύθυνε ειρωνείες περί “φωστήρων”, αλλά πιάστηκε αδιάβαστος
«Βόμβες» Σαμαρά για εθνικά και υποκλοπές: Η Ελλάδα έχει μετατραπεί σε ένα απέραντο φρενοκομείο
Υποκλοπές: Καταψηφίστηκε η πρόταση του ΠΑΣΟΚ για σύσταση Εξεταστικής Επιτροπής- «Βόμβες» Σαμαρά
Υποκλοπές: Στη Βουλή η κρίσιμη μάχη για την εξεταστική – Το Μαξίμου «δείχνει» εθνική ασφάλεια για την απόρριψη
Γκάλοπ
Υποκλοπές: Τι θα κάνει το Μαξίμου με την Εξεταστική – «Λίγη υπομονή…»
Ανδρουλάκης κατά Κακλαμάνη για τις υποκλοπές: «Α λα καρτ ευαισθησίες» – Κλιμακώνεται η πολιτική σύγκρουση
Υποκλοπές: Στην επιτροπή Δεοντολογίας στέλνει ο Κακλαμάνης το θέμα των διαρροών για ΕΥΠ
Δεν είναι αρκετό
Κυβερνητικές πηγές για διαρροή διαλόγου Ανδρουλάκη – Δεμίρη: Ο πρόεδρος του ΠΑΣΟΚ μετεξελίσσεται σε «πράσινη Ζωή»
Επιτροπή Θεσμών και Διαφάνειας: Αναβλήθηκε η συνεδρίαση για την ακρόαση του Κ. Τζαβέλλα μετά την επιστολή του
Υποκλοπές: «Η παρακολούθησή μου διατάχθηκε προφορικά;» – Έντονος διάλογος Ανδρουλάκη-Δεμίρη στην Επιτροπή
Υποκλοπές: Την Παρασκευή η συζήτηση στην ολομέλεια της πρότασης του ΠΑΣΟΚ για εξεταστική επιτροπή
Υποκλοπές: Στην Επιτροπή Θεσμών και Διαφάνειας ο Δεμίρης – «Όχι» από Τζαβέλλα
Νίκος Ανδρουλάκης: Παρών στην ακρόαση του διοικητή της ΕΥΠ, Θ. Δεμίρη, για τις υποκλοπές
Νέα Αριστερά: Ο κ. Τζαβέλλας οφείλει να προσέλθει στην Επιτροπή Θεσμών και Διαφάνειας και να δώσει απαντήσεις
ΠΑΣΟΚ για Τζαβέλλα: Η επίκληση της αρχής της διάκρισης των εξουσιών δεν πείθει κανέναν
Η Επιτροπή Θεσμών περιμένει αύριο Δεμίρη και Τζαβέλλα
«Όχι» Τζαβέλλα στην Επιτροπή Θεσμών για τις υποκλοπές – Επικαλείται διάκριση εξουσιών
Υποκλοπές: Την Τετάρτη στην Eπιτροπή Θεσμών και Διαφάνειας Δεμίρης και Τζαβέλλας
Συνέδριο σε ήρεμα νερά
Υποκλοπές: Επανέρχεται ο Χρήστος Σπίρτζης με ερωτήματα για την πορεία της δικογραφίας
Σκάνδαλο Υποκλοπών: Έρχονται 6 νέες μηνύσεις που «δείχνουν» κατασκοπεία
--- Processing Page 2 ---
«Δεν σχολιάζω κάποιον που είναι ιδιώτης»: Η αμηχανία του Π. Μαρινάκη για τις δηλώσεις του Γρ. Δημητριάδη
Απέφυγε να δώσει απαντήσεις για το σκάνδαλο των υποκλοπών ο Δημητριάδης
Τσουκαλάς: Ελπίζω μετά τον Ντίλιαν που ο πρωθυπουργός μπερδεύει με τον Μπόμπ Ντίλαν, δεν έχει ξεχάσει και τον Δημητριάδη
Υποκλοπές: Η παραδοχη ενοχής του Γρηγόρη Δημητριάδη που «δείχνει» προς το Μέγαρο Μαξίμου
Στην… πρέσατου ΟΠΕΚΕΠΕ και των υποκλοπών
Βενιζέλος: Αιχμές κατά Τζαβέλλα για τη μη ανάσυρση της δικογραφίας των υποκλοπών από το αρχείο
Υποκλοπές: Ανάσυρση της υπόθεσης από το αρχείο και εξαίρεση Τζαβέλλα ζητά ο Σπίρτζης
Human Rights Watch: Καταγγέλλει την Κομισιόν για κενά ελέγχου στις εξαγωγές spyware από την ΕΕ
Τηλεφωνικές υποκλοπές: Παρέμβαση για την πλήρη διερεύνηση της υπόθεσης έκανε και ο Δικηγορικός Σύλλογος Πειραιά
Οι υποκλοπές ως φαντασία ελέγχου
Μαξίμου: Τεστ συνοχής για… γερά νεύρα – Πώς φτάνει στα «όχι» για Προανακριτική και Εξεταστική
ΠΑΣΟΚ: Κατατέθηκε η πρόταση σύστασης Eξεταστικής για τις υποκλοπές – Τι περιλαμβάνει
Eρευνα
Ζαχαρίας Κεσσές για υποκλοπές: Ο Τζαβέλλας αποφάσισε συνειδητά να παραβιάσει τον νόμο, είναι ποινικά ελεγκτέος
Σκάνδαλο υποκλοπών: Πολιτική θύελλα για τον ρόλο Τζαβέλλα και τις παρακολουθήσεις της ΕΥΠ
ΣΥΡΙΖΑ – Υποκλοπές: Ο Εισαγγελέας που «αθώωσε» και τον εαυτό του
Υποκλοπές: Οι 11 στόχοι του Predator που είχε παρακολουθήσει η ΕΥΠ με υπογραφή Τζαβέλλα
Ένωση Εισαγγελέων για την απόφαση του ΔΣΑ περί παραίτησης Τζαβέλλα – «Τέτοιες ενέργειες πλήττουν το κύρος της Δικαιοσύνης»
Ανδρουλάκης: «Ο κ. Μητσοτάκης είναι επικίνδυνος και πρέπει να παραιτηθεί για να αναπνεύσει η χώρα και η δημοκρατία»
Οταν η Κοβέσι ζήτησε να της φέρουν τον Μπακάλη…
Η κραυγή απόγνωσης των βουλευτών…
Δικαστές
Ανδρουλάκης: Πλήττεται ο πυρήνας του κράτους Δικαίου με την αρχειοθέτηση της υπόθεσης των υποκλοπών
Υποκλοπές – Πρόεδροι δικηγορικών συλλόγων: H απόφαση του Άρειου Πάγου οδηγεί σε έλλειψη εμπιστοσύνης των πολιτών προς τη Δικαιοσύνη
Ασφάλεια δικαίου
ΠΑΣΟΚ: Αρραγές μέτωπο με το βλέμμα στις εκλογές
Σκάνδαλο υποκλοπών: Ο Εισαγγελέας του Αρείου Πάγου δεν είδε νεότερα στοιχεία…
Προβληματισμός
Κυριάκος Βελόπουλος για την αρχειοθέτηση της υπόθεσης των υποκλοπών: «Είναι ισοπέδωση της δικαιοσύνης»
ΠΑΣΟΚ για Γεωργιάδη: «Ποιος μπορεί να πάρει στα σοβαρά αυτόν τον πολιτικό κωλοτούμπα;»
Υποκλοπές: Αντιφάσεις στη στάση της κυβέρνησης – Θέλει να αποτρέψει νέα Εξεταστική
Θετικός για σύσταση Εξεταστικής Επιτροπής για τις υποκλοπές ο ΣΥΡΙΖΑ
Υποκλοπές: Συμμαχία για Εξεταστική μετά από τηλεφωνική επικοινωνία Ανδρουλάκη – Φάμελλου – Πέρκα
Υποκλοπές: Τι σημαίνει η πρόταση Ανδρουλάκη για Εξεταστική Επιτροπή – Πώς συγκροτείται
Απότομη διακοπή της συνέντευξης Ανδρουλάκη για τις υποκλοπές (video)
Ν. Ανδρουλάκης: Θα καταθέσουμε αίτημα για Εξεταστική Επιτροπή – Θα καλέσουμε τον κ. Ντίλιαν στη Βουλή
--- Processing Page 3 ---
Υποκλοπές: Θάβεται η υπόθεση στο αρχείο, τι αποφάσισε ο Άρειος Πάγος – Οι αντιδράσεις
Τσίπρας: Ό, τι εύκολα μπαίνει στο αρχείο, το ίδιο εύκολα βγαίνει από το αρχείο
Μαξίμου για υποκλοπές: Το ΠΑΣΟΚ να πάρει αποστάσεις, «χρειάζεται αυτοσυγκράτηση»
Υποκλοπές: Ραγδαίες πολιτικές εξελίξεις μετά την απόφαση του Αρείου Πάγου – Έκτακτη συνέντευξη Τύπου Ανδρουλακη
Απόφαση με πολιτικές διαστάσεις – Στο αρχείο η υπόθεση των υποκλοπών
Άρειος Πάγος: Δεν ανασύρεται από το αρχείο η δικογραφία για τις τηλεφωνικές υποκλοπές
ΣΥΡΙΖΑ: H Intellexa παρουσιαζόταν ως «one stop shop» για κρατικές υποκλοπές και «profiling»
Υποκλοπές: Η Intellexa του Ντίλιαν, με έδρα την Αθήνα, διαφήμιζε κατασκοπευτικά λογισμικά σε «Αρχές επιβολής του νόμου»
ΠΑΣΟΚ: «Ούτε και τώρα η κυβέρνηση θα βγει να διαψεύσει ευθαρσώς τον κ. Ντίλιαν;»
Βουλευτής ΝΔ
Σεβασμός
Φάμελλος: Κύριε Μητσοτάκη είστε ένας διαπλεκόμενος και εκβιαζόμενος πρωθυπουργός – Eσείς είστε το βαθύ κράτος
Βουλή: Το σκάνδαλο των υποκλοπών στο επίκεντρο της συνεδρίασης
Η Ανάσταση, πέραν του μεταφυσικού
Κ. Τσουκαλάς: Οι υποκλοπές και ο ΟΠΕΚΕΠΕ δεν είναι σκάνδαλα του απρόσωπου «βαθέος κράτους», αλλά μιας προσωποπαγούς δομής εξουσίας
Υποκλοπές: Πολιτικός σεισμός από την αποκάλυψη των «ΝΕΩΝ» – Μπαράζ παραγραφών φέρνουν οι καθυστερήσεις του Αρείου Πάγου
Υποκλοπές: Επιχείρηση παραγραφής – Τα 13 βήµατα στο παρασκήνιο
Υποκλοπές: Στο εδώλιο στις 11 Δεκεμβρίου οι τέσσερις επιχειρηματίες που καταδικάστηκαν
Υποκλοπές: Η δικογραφία «σπάει στα δύο» – Ξεκινούν τέσσερις νέες έρευνες
Μια λύση
Από τα Τέμπη στις υποκλοπές: Η πολιτική κρίση που βαραίνει την κυβέρνηση
«Πώς αγοράσατε το Predator;»: Πολιτική θύελλα μετά τις αποκαλύψεις για κρατική χρηματοδότηση της Intellexa
Γιατί η ελληνική Φιλελεύθερη Δημοκρατία είναι σε κρίση;
Αλέξης Τσίπρας: «Ο Κ. Μητσοτάκης να παραιτηθεί όπως ο Νίξον – Η μόνη σχέση του με την Ευρώπη είναι αυτή με την Ευρωπαϊκή Εισαγγελία»
Ανδρουλάκης: Εκλογές να τελειώνουμε  – Να μπει τέλος στην ατιμωρησία
Ο πήχης
Μετατίθεται η προ ημερήσιας συζήτηση στη Βουλή για το Κράτος Δικαίου - Θα πραγματοποιηθεί στις 17 Απριλίου, η αντίδραση ΠΑΣΟΚ
ΠΑΣΟΚ: Τι φοβάται το Μέγαρο Μαξίμου και δεν διαψεύδει τον ιδιοκτήτη της Intellexa;
Η υποκλοπή των θεσμών
Άδωνις Γεωργιάδης στο MEGA: Δεν έχω κανένα πρόβλημα που με παρακολουθούσαν
Σκάνδαλο Υποκλοπών: Εννέα πρόσωπα στέλνει στο εδώλιο η πρώτη απόφαση
Σκάνδαλο υποκλοπών: Και τώρα έρευνα για κατασκοπεία
Στα «ύψη» η πολιτική αντιπαράθεση μετά τις δηλώσεις «βόμβα» του Ταλ Ντίλιαν στο MEGA για τις υποκλοπές και το Predator
Οι ανοιχτοί λογαριασμοί, οι «μανούβρες» – Στη ΝΔ ανησυχούν για αποκαλύψεις
Με την πλάτη στον τοίχο
Σενάρια για αλλαγές στον Ποινικό Κώδικα με αφορμή τις υποκλοπές
--- Processing Page 4 ---
Υποκλοπές: Γραμμή απαξίωσης από Μαξίμου – «Κλειδώνει» η μάχη κορυφής στη Βουλή
Παύλος Μαρινάκης: Τι είπε για κατώτατο μισθό, υποκλοπές και Τέμπη
Χάρης Δούκας στο MEGA: «Βασικός στόχος του ΠΑΣΟΚ να φύγει η ΝΔ – Καμία συνεργασία με την κυβέρνηση των υποκλοπών»
Υποκλοπές: Η δήλωση «βόμβα» Ντίλιαν στο MEGA Stories και Inside Story και οι αντιδράσεις
Το 20ήμερο των «Παθών» για το Μαξίμου και οι Συμπληγάδες υποκλοπών, Τεμπών και ΟΠΕΚΕΠΕ
Predator: Ποιος υπουργός και πότε υπέγραψε για την αγορά του λογισμικού κατασκοπείας
ΠΑΣΟΚ μετά τις νέες δηλώσεις Ταλ Ντίλιαν: Το νοσηρό και δυσώδες παρακράτος ξηλώνεται
Τι ήταν το σκάνδαλο Watergate που επικαλέστηκε ο Ταλ Ντίλιαν: Και πώς η ελευθερία του Τύπου έσωσε τη Δημοκρατία
Βαρίδια
Υποκλοπές: Ανοίγει ο δρόμος για την έρευνα για κατασκοπεία
Ανοικτή επιστολή Ανδρουλάκη «προς όλους τους Δημόσιους Αξιωματούχους, που υπήρξαν στόχοι των υποκλοπών και του Predator»
Το χαλί
Το πρώτο ευρω-πρόστιμο για το πάρτι της «κατάρτισης»
Υπόθεση υποκλοπών: Ο νέος Δαρβινισμός και οι κήνσορές του που αλυχτούν
Κουτσούμπας: Ο Κυριάκος Μητσοτάκης θα φύγει, έχει δρομολογηθεί μέσα από το κόμμα της ΝΔ
Υποκλοπές, ΟΠΕΚΕΠΕ, Παναγόπουλος: Οι νέες αποκαλύψεις για τις ανοιχτές πληγές
ΠΑΣΟΚ για υποκλοπές: Η κυβέρνηση δεν θα αποφύγει τη λογοδοσία για το παρακράτος που έστησε
Κ. Τσουκαλάς: «Η κυβέρνηση είναι βαρύτατα εκτεθειμένη και δεν θα αποφύγει τη λογοδοσία για το παρακράτος που έστησε»
Κυρ.Βελόπουλος: Απ’ ό,τι ξέρουμε έρχονται κι άλλες αποκαλύψεις που καίνε και κάποιοι θα χάσουν τη μιλιά τους
«Σημείο καμπής» η δήλωση Ντίλιαν για τις υποκλοπές λέει ο δικηγόρος θυμάτων του Predator
Ο ιδρυτής της Intellexa καίει το Μαξίμου για το Predator: «Πελάτες μας μόνο κυβερνήσεις» – Καταρρέει το αφήγημα περί ιδιωτών
Υποκλοπές: Έρχονται νομικές κινήσεις από άλλα τρία θύματα
Πυρ ομαδόν της αντιπολίτευσης για τις υποκλοπές: «Εργαλείο του Μαξίμου το predator»
Σ. Φάμελλος: Οι δηλώσεις Ντίλιαν επιβεβαιώνουν ξεκάθαρα την εμπλοκή της κυβέρνησης στο σκάνδαλο των υποκλοπών
Δείχνει την κυβέρνηση ο Ντίλιαν για το σκάνδαλο υποκλοπών: «Παρέχουμε τεχνολογία μόνο σε κυβερνήσεις και αρχές επιβολής του νόμου»
MEGA Stories – Υποκλοπές: Η καταδίκη των 4ων και οι αόρατοι εντολείς απόψε στις 00:40
«MEGA Stories» – Υποκλοπές: Η καταδίκη των 4 και οι αόρατοι εντολείς
Δημοσκόπηση Αlco: Άπιαστο όνειρο η αυτοδυναμία - «Επιστροφή έκπληξη» στη Βουλή και δυσαρέσκεια πολιτών για ακρίβεια και υποκλοπές
Υποκλοπές: «Η λίστα Μενουδάκου» -115 υπουργοί, βουλευτές, στελέχη, επιχειρηματίες, δημοσιογράφοι
Υποκλοπές: H εκτροπή στην Γ’ Ελληνική Δημοκρατία
To «Ενιαίο Αμυντικό Δόγμα»…
Ανδρουλάκης: Αίτημα για προ ημερησίας συζήτηση στη Βουλή για το κράτος δικαίου
Μέγαρο Μαξίμου: Παλιοί λογαριασμοί και νέες πιέσεις
Γεροβασίλη στο “Tonight”: «Το σκάνδαλο των υποκλοπών ανοίγει ξανά – Υπάρχουν ευθύνες με ονοματεπώνυμο»
«Μέγιστο σκάνδαλο υποκλοπών»: Τα διεθνή μέσα για εξέλιξη της υπόθεσης Predator
Υποκλοπές: Ύβρις και τιμωρία
--- Processing Page 5 ---
Κατά συμβεβηκός
Ανδρουλάκης σε Μητσοτάκη για υποκλοπές:  « Ιστορική δικαστική απόφαση, μεγάλη ήττα του παρακράτους»
Η αντιπολίτευση «δείχνει» Μαξίμου μετά την απόφαση για τις υποκλοπές – Οι κατηγορίες για παρακράτος και η επόμενη μέρα
«Μάχη» στη Βουλή σήμερα για τις υποκλοπές – Εξηγήσεις Μητσοτάκη, σφυροκόπημα Ανδρουλάκη
Εξώδικο στον Αλέξη Τσίπρα έστειλε ο Γρηγόρης Δημητριάδης – «Επιχειρεί να με εκβιάσει» λέει ο πρώην πρωθυπουργός
Παπανδρέου για υποκλοπές: Πλήρη διαλεύκανση και τιμωρία όλων των υπευθύνων όσο ψηλά κι αν βρίσκονται
Ανδρουλάκης για υποκλοπές: Θα λογοδοτήσουν όλοι, όσο ψηλά κι αν βρίσκονται - Ακόμα και ο Μητσοτάκης και ο Δημητριάδης
Χαρίτσης: Η σημερινή δικαστική απόφαση για τις υποκλοπές αφήνει έκθετη την κυβέρνηση
Φάμελλος: Υπήρξε οργανωμένο σχέδιο υποκλοπών και παρακολουθήσεων με πρακτικές παρακράτους
Υπόθεση υποκλοπών: Αντίστροφη μέτρηση για την ετυμηγορία
Η ώρα της κρίσης για την υπόθεση των υποκλοπών
Υπαινιγμοί
Το σύστημα
ΠΑΣΟΚ: Δικαίωση για τον Ν. Ανδρουλάκη η εισαγγελική πρόταση για τις υποκλοπές
Δίκη υποκλοπών: Την ενοχή και  4 κατηγορουμένων για 3 αδικήματα πρότεινε ο εισαγγελέας – Η πρόταση «καταπέλτης»
Νέα δικογραφία για τις υποκλοπές
Νίκος Ανδρουλάκης: Ξαναφέρνει στο προσκήνιο τις υποκλοπές
Στην τελική ευθεία η δίκη για την υπόθεση των υποκλοπών
Σύνταγμα
Η ανατομία του «υβριδικού κράτους»
Κρεαταγορά
Υποκλοπές: Όσα «είπε» η κάρτα από την οποία έφυγε το «μολυσμένο» μήνυμα με παραλήπτη τον Νίκο Ανδρουλάκη
Υποκλοπές: Απάντηση από την Εθνική Τράπεζα για την κίνηση της κάρτας που έφυγε το μολυσμένο μήνυμα στον Ν. Ανδρουλάκη
Παγίδα
Μία (ακόμη) ήττα στα απόνερα των υποκλοπών
ΣΥΡΙΖΑ: Ο Μητσοτάκης δεν θα ξεφύγει από τις ευθύνες του για την υπόθεση των υποκλοπών
Δίκη υποκλοπών: Τη σχέση του κατηγορούμενου Γ. Λαβράνου με την εταιρεία krilel επιβεβαίωσε μάρτυρας
Υποκλοπές: Νέα στοιχεία αποκαλύφθηκαν στη δίκη – Αμφισβητήθηκε η αξιοπιστία μάρτυρα και από την έδρα
ΠΑΣΟΚ: Κατά προτεραιότητα εξέταση της προσφυγής Ανδρουλάκη από το ΕΔΑΔ για τις υποκλοπές
ΠΑΣΟΚ: Ένοχη σιωπή της κυβέρνησης μπροστά στις συνεχείς αποκαλύψεις στη δίκη του predator
Υποκλοπές: Για κοινό βραχίονα ΕΥΠ και predator κατέθεσε ο Κ. Βαξεβάνης
Υποκλοπές: Δέκα νέοι μάρτυρες στη δίκη – Καλείται ο «κρεοπώλης»
Σκάνδαλο υποκλοπών: έγκλημα χωρίς τιμωρία;
Δίκη υποκλοπών: Σημαντικά στοιχεία κατέθεσε ο δημοσιογράφος των ΝΕΩΝ Βασίλης Λαμπρόπουλος
Η μούγγα
Δίκη για τηλεφωνικές υποκλοπές: Καλούνται δέκα νέοι μάρτυρες
--- Processing Page 6 ---
Εξηγήσεις για το «φροντιστήριο»
Δίκη υποκλοπών: Στα προσκόμματα της έρευνας αναφέρθηκε ο πρώην πρόεδρος της ΑΔΑΕ Χρ. Ράμμος – Νέα στοιχεία για την εταιρεία Krikel
Τρεις καταθέσεις-κλειδιά για τις υποκλοπές
Καμία εθνική ασφάλεια
Πολλά… αφτιά για τις υποκλοπές μέσω Predator
ΣΥΡΙΖΑ, ΠΑΣΟΚ και Νέα Αριστερά ζητούν έκτακτη σύγκληση της Επιτροπής Θεσμών και Διαφάνειας
ΠΑΣΟΚ: Το σκάνδαλο των υποκλοπών δεν θα κλείσει με πολιτικές μεθοδεύσεις και συγκάλυψη
Δίκη για υποκλοπές: Η αδύναμη μνήμη και οι αντιφάσεις
Δίκη υποκλοπών: Μάρτυρας παραδέχεται επιστροφή στην Intellexa ενώ η υπόθεση βρισκόταν στο «μικροσκόπιο» των Αρχών
Σιωπή για το «σκονάκι» στην Εξεταστική
Υποκλοπές: Ελεγξαν… άδειες αίθουσες στην ΕΥΠ
Δίκη για τις υποκλοπές: «Ο έλεγχος της ΑΔΑΕ στην ΕΥΠ ήταν επιφανειακός» – Αποκαλυπτική κατάθεση μάρτυρα
Οι υποκλοπές ξανά στην πόρτα της κυβέρνησης
Διδακτικά
Κατάθεση Κουκάκη: «Ενιαίο κέντρο τηλεφωνικών παρακολουθήσεων ΕΥΠ – Predator»
Πρώην προϊσταμένη των Εγκληματολογικών Εργαστηρίων: «ΕΥΠ και Predator με παρακολουθούσαν»
«Έλαβα απειλητικό email για συμβόλαιο θανάτου» - Αποκαλύψεις στη δίκη των υποκλοπών
Ιθάκη – Predator 0-1
Η ασφυξία στις φυλακές φέρνει περισσότερα «βραχιολάκια»
Υποκλοπές – Κατάθεση βόμβα: «Μου έδωσαν έτοιμες τις περισσότερες ερωτήσεις και απαντήσεις για την Εξεταστική»
Δίκη υποκλοπών: Αν το πολιτικό σύστημα είχε σταθεί στο ύψος του, όλοι οι υπεύθυνοι θα δικάζονταν – Αποκαλυπτική κατάθεση Κουκάκη
Δίκη υποκλοπών: Αποκαλυπτική κατάθεση Θ. Κουκάκη κατά ΕΥΠ – «Με κατέγραφαν μέχρι και στο σχολείο της κόρης μου»
Yπόθεση υποκλοπών: Την ΕΥΠ δείχνει ως υπεύθυνη για την παρακολούθηση της πρώην υπάλληλος της Υπηρεσίας
Ανδρουλάκης: Θα πάμε την υπόθεση του Predator μέχρι το τέλος
Έκρηξη στις υποκλοπές χωρίς αιτιολογία: Τι αναφέρεται στην τελευταία έκθεση της ΑΔΑΕ
Χάθηκαν και πάλι στη μετάφραση στη δίκη για τις υποκλοπές
Η νέα πολιτική
Νέοι κίνδυνοι για την ιδιωτικότητα από τα ραντάρ
Οι έξι δύσκολοι Αύγουστοι του Μαξίμου
Στραβή
Παραίτηση
Ραντεβού τον Σεπτέμβρη και με τις υποκλοπές
Επανέρχεται στο δικαστικό προσκήνιο η υπόθεση των υποκλοπών: Στις 24 Σεπτεμβρίου η εκδίκαση
Πενήντα ένα χρόνια απ’ το 1974: Τι θέλουμε;
Η επίθεση της Ζωής «σφράγισε» την πρωτιά του Βασίλη Φλωρίδη
Υποκλοπές: Στο κενό οι ενστάσεις των κατηγορουμένων
--- Processing Page 7 ---
Υποκλοπές: «Όχι» από Άρειο Πάγο σε Ανδρουλάκη και Κουκάκη για ανάσυρση από το αρχείο της υπόθεσης του κρεοπώλη
Στη δίνη νέου σκανδάλου υποκλοπών
Υποκλοπές Νο 2 με νέο κακόβουλο λογισμικό – Με στόχους και στην Ελλάδα
Υποκλοπές: Η νέα αρχειοθέτηση αύξησε τα ερωτήματα
Υποκλοπές: Στο αρχείο η μήνυση Ανδρουλάκη
Υποκλοπές: Θα κληθεί για κατάθεση ο κρεοπώλης;
Στον εισαγγελέα ο κρεοπώλης των υποκλοπών - Μήνυση από Ανδρουλάκη
Στα «ΝΕΑ» της Τετάρτης: Στον εισαγγελέα ο κρεοπώλης των υποκλοπών
Ο κρεοπώλης, οι υποκλοπές και τα νέα ερωτήματα
Ομιλία Αλέξη Τσίπρα με αιχμές για υποκλοπές, Τέμπη και ναυάγιο της Πύλου
Ο κρεοπώλης, οι υποκλοπές και τα νέα ερωτήματα
Μείωσαν κατά 31% τις ασύδοτες παρακολουθήσεις
Μείωση κατά 31% τον τελευταίο χρόνο από ΕΥΠ και ΕΛ.ΑΣ.
Υποκλοπές: Μια απόφαση – σταθμός και τα μηνύματα
Μια απόφαση – σταθμός και τα μηνύματα
Δίκαιο
Απορρίφθηκε η αγωγή Slapp του Δημητριάδη
Δίκαιο
Ο πρόεδρος της ΑΔΑΕ και το τραύμα των υποκλοπών στη δημοκρατία
Ο πρόεδρος της ΑΔΑΕ και το τραύμα των υποκλοπών στη δημοκρατία
Σκάνδαλο υποκλοπών: Πώς εμποδίστηκε ο Ράμμος να ενημερώσει τη Βουλή
Εισαγγελική έρευνα και στην Ελβετία για τις υποκλοπές
Εισαγγελική έρευνα και στην Ελβετία για τις υποκλοπές
Τουρκικές γραφικότητες στη βραχονησίδα Ζουράφα
Τουρκικές γραφικότητες στη βραχονησίδα Ζουράφα
Νέα «μαύρη λίστα» από το Στέιτ Ντιπάρτμεντ για τις υποκλοπές
Νέα «μαύρη λίστα» από το Στέιτ Ντιπάρτμεντ για τις υποκλοπές
Και η Ιντερπόλ… γνωμοδοτεί για τους πρωταγωνιστές των υποκλοπών
Ξανά στο κάδρο των υποκλοπών η Λευκωσία
Ξανά στο κάδρο των υποκλοπών η Λευκωσία
Το παράδοξο
Νέα «καμπάνα» από τις ΗΠΑ για το Predator
Το παράδοξο
Αίσθηση
Αίσθηση
Δημοκρατική απάθεια: από τις υποκλοπές ως τις φυσικές καταστροφές

In [5]:
teaser_articles_list = []

start_page = 1
end_page = 7
base_tag_url = 'https://www.tanea.gr/tag/%CF%85%CF%80%CE%BF%CE%BA%CE%BB%CE%BF%CF%80%CE%AD%CF%82/'

for page_num in range(start_page, end_page + 1):
    print(f"--- Processing Page {page_num} ---")

    if page_num == 1:
        page_url = base_tag_url
    else:
        page_url = f"{base_tag_url}page/{page_num}/"

    try:
        response_page = requests.get(page_url)
        response_page.raise_for_status() # Raise an HTTPError for bad responses (4xx or 5xx)
        doc = BeautifulSoup(response_page.text, 'html.parser') # Update doc for each page
    except requests.exceptions.RequestException as e:
        print(f"Could not fetch page {page_url}: {e}")
        continue # Skip to the next page if page fetch fails

    for i in range(1, 37):
        # Construct the class string for the current iteration
        current_class_name = f'column is-full ro_{i}'

        # Find all divs with the constructed class name on the current page's doc
        found_articles_for_i = doc.find_all('div', class_=current_class_name)

        if found_articles_for_i:
            # Add these articles to the main list
            teaser_articles_list.extend(found_articles_for_i)

            # Iterate through the articles found in this specific 'ro_i' class
            # and print their headlines and other details
            for article_element in found_articles_for_i:
                headline = article_element.find('h3')
                if headline:
                    print(f"Headline: {headline.text.strip()}")
                else:
                    print(f"No headline found for an article in '{current_class_name}'")

                # Extract and print category
                category_element = article_element.find('span', {'class': 'is-bold is-size-4-desktop is-size-5-touch'})
                if category_element:
                    print(f"Category: {category_element.text.strip()}")
                else:
                    print(f"No category found for an article in '{current_class_name}'")

                # Extract and print author
                author_element = article_element.find('span', {'class': 'is-semibold mr-4 uppercase is-size-5 is-neablue mb-1'})
                if author_element:
                    print(f"Author: {author_element.text.strip()}")
                else:
                    print(f"No author found for an article in '{current_class_name}'")

                # Extract and print date
                date_element = article_element.find('span', {'class': 'is-size-5 is-darkblue'})
                if date_element:
                    print(f"Date: {date_element.text.strip()}")
                else:
                    print(f"No date found for an article in '{current_class_name}'")
                print("-" * 20) # Separator for clarity between articles
        else:
            print(f"No articles found for class '{current_class_name}' on this page.")

--- Processing Page 1 ---
Headline: Απάντηση Τσουκαλά σε Φλωρίδη: Να ανασυρθεί από το αρχείο η υπόθεση των παράνομων υποκλοπών
Category: Πολιτική
No author found for an article in 'column is-full ro_1'
Date: 09/06/2026 16:39
--------------------
Headline: Υποκλοπές: Νέα πολιτική θύελλα μετά τις αποκαλύψεις για συμφωνητικό με την ΕΥΠ
Category: Πολιτική
No author found for an article in 'column is-full ro_2'
Date: 07/06/2026 16:38
--------------------
Headline: Μαξίμου για αίτημα ΠΑΣΟΚ να κληθεί στη Βουλή ο Ντίλιαν: «Θα αποφασίσουν τα αρμόδια όργανα»
Category: Πολιτική
Author: Ελένη Ευαγγελοδήμου
Date: 04/06/2026 13:20
--------------------
Headline: Υποκλοπές: Ντόμινο εξελίξεων μετά τις δηλώσεις Ντίλιαν – Ο Κουκάκης ζητά ανάσυρση του φακέλου από το αρχείο
Category: Ελλάδα
Author: Μίνα Μουστάκα
Date: 04/06/2026 12:24
--------------------
Headline: Υποκλοπές: Αίτημα του ΠΑΣΟΚ για ακρόαση στην Επιτροπή Θεσμών και Διαφάνειας των Ταλ Ντίλιαν και Γρηγόρη Δημητριάδη
Category: Πολιτική
No author found for an article in 'column is-full ro_5'
Date: 02/06/2026 17:03
--------------------
Headline: ΕΛΑΣ για δηλώσεις Ντίλιαν: «Ο κ. Μητσοτάκης δεν μπορεί άλλο να κρύβεται – Να δώσει απαντήσεις και στοιχεία»
Category: Πολιτική
Author: TANEA Newsroom
Date: 02/06/2026 11:18
--------------------
Headline: Υποκλοπές: Ντίλιαν καρφώνει κυβέρνηση – «Πουλάμε μόνο σε κρατικές αρχές, δεν λειτουργούμε τα συστήματα οι ίδιοι»
Category: Ελλάδα
No author found for an article in 'column is-full ro_7'
Date: 02/06/2026 10:39
--------------------
Headline: Κ. Τσουκαλάς: Δημοκρατικό καθήκον προς τους πολίτες η διαλεύκανση των παράνομων παρακολουθήσεων
Category: Πολιτική
No author found for an article in 'column is-full ro_8'
Date: 02/06/2026 09:51
--------------------
Headline: Κεσσές για υποκλοπές: Σκυταλοδρομία συγκάλυψης – Προβληματική η ανάθεση της υπόθεσης από τον Τζαβέλλα στον Μπακέλα
Category: Ελλάδα
No author found for an article in 'column is-full ro_9'
Date: 27/05/2026 13:09
--------------------
Headline: Ηρεμα νερά
Category: Απόψεις, Σχόλια & Γνώμες
Author: Παπασπύρος Νίκος
Date: Πρώτη Δημοσιεύση:25/05/2026 18:46
--------------------
Headline: «Ypoklopes Blues»
Category: Απόψεις, Σχόλια & Γνώμες
Author: Γιάννης Φ. Ιωαννίδης
Date: Πρώτη Δημοσιεύση:23/05/2026 18:15
--------------------
Headline: Τσουκαλάς: A λα καρτ αντίληψη της εθνικής ασφάλειας από την κυβέρνηση – Να ζητήσει συγγνώμη από τον Ανδρουλάκη
Category: Πολιτική
No author found for an article in 'column is-full ro_12'
Date: 23/05/2026 13:42
--------------------
Headline: Χάχανο
Category: Μερική άγνοια
Author: Κώστας Γιαννακίδης
Date: Πρώτη Δημοσιεύση:22/05/2026 14:15
--------------------
Headline: Κ. Τσουκαλάς: Ο κ. Φλωρίδης με περισπούδαστο ύφος απηύθυνε ειρωνείες περί “φωστήρων”, αλλά πιάστηκε αδιάβαστος
Category: Πολιτική
No author found for an article in 'column is-full ro_14'
Date: 22/05/2026 13:56
--------------------
Headline: «Βόμβες» Σαμαρά για εθνικά και υποκλοπές: Η Ελλάδα έχει μετατραπεί σε ένα απέραντο φρενοκομείο
Category: Πολιτική
No author found for an article in 'column is-full ro_15'
Date: 22/05/2026 12:23
--------------------
Headline: Υποκλοπές: Καταψηφίστηκε η πρόταση του ΠΑΣΟΚ για σύσταση Εξεταστικής Επιτροπής- «Βόμβες» Σαμαρά
Category: Πολιτική
No author found for an article in 'column is-full ro_16'
Date: 22/05/2026 10:31
--------------------
Headline: Υποκλοπές: Στη Βουλή η κρίσιμη μάχη για την εξεταστική – Το Μαξίμου «δείχνει» εθνική ασφάλεια για την απόρριψη
Category: Πολιτική
No author found for an article in 'column is-full ro_17'
Date: 22/05/2026 09:00
--------------------
Headline: Γκάλοπ
Category: Πίσω από τις κάμερες
Author: Μυρτώ Λιαλιούτη
Date: Πρώτη Δημοσιεύση:21/05/2026 15:07
--------------------
Headline: Υποκλοπές: Τι θα κάνει το Μαξίμου με την Εξεταστική – «Λίγη υπομονή…»
Category: Πολιτική
Author: Ελένη Ευαγγελοδήμου
Date: 21/05/2026 13:16
--------------------
Headline: Ανδρουλάκης κατά Κακλαμάνη για τις υποκλοπές: «Α λα καρτ ευαισθησίες» – Κλιμακώνεται η πολιτική σύγκρουση
Category: Πολιτική
No author found for an article in 'column is-full ro_20'
Date: 20/05/2026 19:49
--------------------
Headline: Υποκλοπές: Στην επιτροπή Δεοντολογίας στέλνει ο Κακλαμάνης το θέμα των διαρροών για ΕΥΠ
Category: Πολιτική
No author found for an article in 'column is-full ro_21'
Date: 20/05/2026 15:55
--------------------
Headline: Δεν είναι αρκετό
Category: Αγιογραφίες
Author: Μιχάλης Μητσός
Date: Πρώτη Δημοσιεύση:20/05/2026 15:17
--------------------
Headline: Κυβερνητικές πηγές για διαρροή διαλόγου Ανδρουλάκη – Δεμίρη: Ο πρόεδρος του ΠΑΣΟΚ μετεξελίσσεται σε «πράσινη Ζωή»
Category: Πολιτική
No author found for an article in 'column is-full ro_23'
Date: 20/05/2026 15:10
--------------------
Headline: Επιτροπή Θεσμών και Διαφάνειας: Αναβλήθηκε η συνεδρίαση για την ακρόαση του Κ. Τζαβέλλα μετά την επιστολή του
Category: Πολιτική
No author found for an article in 'column is-full ro_24'
Date: 20/05/2026 14:32
--------------------
Headline: Υποκλοπές: «Η παρακολούθησή μου διατάχθηκε προφορικά;» – Έντονος διάλογος Ανδρουλάκη-Δεμίρη στην Επιτροπή
Category: Πολιτική
Author: Μυρτώ Λιαλιούτη
Date: 20/05/2026 14:02
--------------------
Headline: Υποκλοπές: Την Παρασκευή η συζήτηση στην ολομέλεια της πρότασης του ΠΑΣΟΚ για εξεταστική επιτροπή
Category: Πολιτική
No author found for an article in 'column is-full ro_26'
Date: 20/05/2026 11:24
--------------------
Headline: Υποκλοπές: Στην Επιτροπή Θεσμών και Διαφάνειας ο Δεμίρης – «Όχι» από Τζαβέλλα
Category: Πολιτική
No author found for an article in 'column is-full ro_27'
Date: 20/05/2026 10:55
--------------------
Headline: Νίκος Ανδρουλάκης: Παρών στην ακρόαση του διοικητή της ΕΥΠ, Θ. Δεμίρη, για τις υποκλοπές
Category: Πολιτική
No author found for an article in 'column is-full ro_28'
Date: 20/05/2026 10:23
--------------------
Headline: Νέα Αριστερά: Ο κ. Τζαβέλλας οφείλει να προσέλθει στην Επιτροπή Θεσμών και Διαφάνειας και να δώσει απαντήσεις
Category: Πολιτική
No author found for an article in 'column is-full ro_29'
Date: 19/05/2026 15:17
--------------------
Headline: ΠΑΣΟΚ για Τζαβέλλα: Η επίκληση της αρχής της διάκρισης των εξουσιών δεν πείθει κανέναν
Category: Πολιτική
No author found for an article in 'column is-full ro_30'
Date: 19/05/2026 15:11
--------------------
Headline: Η Επιτροπή Θεσμών περιμένει αύριο Δεμίρη και Τζαβέλλα
Category: ΜικροΠολιτικός
Author: Ο μικροπολιτικός
Date: Πρώτη Δημοσιεύση:19/05/2026 14:10
--------------------
Headline: «Όχι» Τζαβέλλα στην Επιτροπή Θεσμών για τις υποκλοπές – Επικαλείται διάκριση εξουσιών
Category: Ελλάδα
Author: Μίνα Μουστάκα
Date: 19/05/2026 12:05
--------------------
Headline: Υποκλοπές: Την Τετάρτη στην Eπιτροπή Θεσμών και Διαφάνειας Δεμίρης και Τζαβέλλας
Category: Ελλάδα
No author found for an article in 'column is-full ro_33'
Date: 18/05/2026 16:51
--------------------
Headline: Συνέδριο σε ήρεμα νερά
Category: Στίγμα
Author: Γιώργος Παπαχρήστος
Date: Πρώτη Δημοσιεύση:15/05/2026 14:20
--------------------
Headline: Υποκλοπές: Επανέρχεται ο Χρήστος Σπίρτζης με ερωτήματα για την πορεία της δικογραφίας
Category: Πολιτική
Author: Μίνα Μουστάκα
Date: 14/05/2026 17:44
--------------------
Headline: Σκάνδαλο Υποκλοπών: Έρχονται 6 νέες μηνύσεις που «δείχνουν» κατασκοπεία
Category: Ελλάδα
No author found for an article in 'column is-full ro_36'
Date: 13/05/2026 19:25
--------------------
--- Processing Page 2 ---
Headline: «Δεν σχολιάζω κάποιον που είναι ιδιώτης»: Η αμηχανία του Π. Μαρινάκη για τις δηλώσεις του Γρ. Δημητριάδη
Category: Πολιτική
No author found for an article in 'column is-full ro_1'
Date: 11/05/2026 16:40
--------------------
Headline: Απέφυγε να δώσει απαντήσεις για το σκάνδαλο των υποκλοπών ο Δημητριάδης
Category: Ελλάδα
No author found for an article in 'column is-full ro_2'
Date: 11/05/2026 14:03
--------------------
Headline: Τσουκαλάς: Ελπίζω μετά τον Ντίλιαν που ο πρωθυπουργός μπερδεύει με τον Μπόμπ Ντίλαν, δεν έχει ξεχάσει και τον Δημητριάδη
Category: Πολιτική
No author found for an article in 'column is-full ro_3'
Date: 11/05/2026 10:19
--------------------
Headline: Υποκλοπές: Η παραδοχη ενοχής του Γρηγόρη Δημητριάδη που «δείχνει» προς το Μέγαρο Μαξίμου
Category: Πολιτική
No author found for an article in 'column is-full ro_4'
Date: 10/05/2026 17:55
--------------------
Headline: Στην… πρέσατου ΟΠΕΚΕΠΕ και των υποκλοπών
Category: Ελλάδα
Author: Μίνα Μουστάκα
Date: Πρώτη Δημοσιεύση:10/05/2026 14:25
--------------------
Headline: Βενιζέλος: Αιχμές κατά Τζαβέλλα για τη μη ανάσυρση της δικογραφίας των υποκλοπών από το αρχείο
Category: Πολιτική
No author found for an article in 'column is-full ro_6'
Date: 09/05/2026 21:24
--------------------
Headline: Υποκλοπές: Ανάσυρση της υπόθεσης από το αρχείο και εξαίρεση Τζαβέλλα ζητά ο Σπίρτζης
Category: Πολιτική
Author: Μίνα Μουστάκα
Date: 07/05/2026 13:02
--------------------
Headline: Human Rights Watch: Καταγγέλλει την Κομισιόν για κενά ελέγχου στις εξαγωγές spyware από την ΕΕ
Category: Κόσμος
No author found for an article in 'column is-full ro_8'
Date: 06/05/2026 09:39
--------------------
Headline: Τηλεφωνικές υποκλοπές: Παρέμβαση για την πλήρη διερεύνηση της υπόθεσης έκανε και ο Δικηγορικός Σύλλογος Πειραιά
Category: Ελλάδα
No author found for an article in 'column is-full ro_9'
Date: 05/05/2026 20:31
--------------------
Headline: Οι υποκλοπές ως φαντασία ελέγχου
Category: Απόψεις, Σχόλια & Γνώμες
Author: Λευτέρης Κουσούλης
Date: Πρώτη Δημοσιεύση:05/05/2026 18:31
--------------------
Headline: Μαξίμου: Τεστ συνοχής για… γερά νεύρα – Πώς φτάνει στα «όχι» για Προανακριτική και Εξεταστική
Category: Πολιτική
Author: Ελένη Ευαγγελοδήμου
Date: 05/05/2026 06:22
--------------------
Headline: ΠΑΣΟΚ: Κατατέθηκε η πρόταση σύστασης Eξεταστικής για τις υποκλοπές – Τι περιλαμβάνει
Category: Πολιτική
No author found for an article in 'column is-full ro_12'
Date: 04/05/2026 14:22
--------------------
Headline: Eρευνα
Category: ΚΥΡΙΟ ΑΡΘΡΟ
Author: ΤΑ ΝΕΑ
Date: Πρώτη Δημοσιεύση:04/05/2026 14:00
--------------------
Headline: Ζαχαρίας Κεσσές για υποκλοπές: Ο Τζαβέλλας αποφάσισε συνειδητά να παραβιάσει τον νόμο, είναι ποινικά ελεγκτέος
Category: Ελλάδα
No author found for an article in 'column is-full ro_14'
Date: 02/05/2026 16:57
--------------------
Headline: Σκάνδαλο υποκλοπών: Πολιτική θύελλα για τον ρόλο Τζαβέλλα και τις παρακολουθήσεις της ΕΥΠ
Category: Ελλάδα
No author found for an article in 'column is-full ro_15'
Date: 02/05/2026 16:32
--------------------
Headline: ΣΥΡΙΖΑ – Υποκλοπές: Ο Εισαγγελέας που «αθώωσε» και τον εαυτό του
Category: Πολιτική
No author found for an article in 'column is-full ro_16'
Date: 02/05/2026 14:56
--------------------
Headline: Υποκλοπές: Οι 11 στόχοι του Predator που είχε παρακολουθήσει η ΕΥΠ με υπογραφή Τζαβέλλα
Category: Ελλάδα
No author found for an article in 'column is-full ro_17'
Date: 02/05/2026 14:08
--------------------
Headline: Ένωση Εισαγγελέων για την απόφαση του ΔΣΑ περί παραίτησης Τζαβέλλα – «Τέτοιες ενέργειες πλήττουν το κύρος της Δικαιοσύνης»
Category: Ελλάδα
Author: Μίνα Μουστάκα
Date: 30/04/2026 19:42
--------------------
Headline: Ανδρουλάκης: «Ο κ. Μητσοτάκης είναι επικίνδυνος και πρέπει να παραιτηθεί για να αναπνεύσει η χώρα και η δημοκρατία»
Category: Πολιτική
No author found for an article in 'column is-full ro_19'
Date: 30/04/2026 18:58
--------------------
Headline: Οταν η Κοβέσι ζήτησε να της φέρουν τον Μπακάλη…
Category: ΜικροΠολιτικός
Author: ο μικρο-πολιτικος
Date: Πρώτη Δημοσιεύση:30/04/2026 14:10
--------------------
Headline: Η κραυγή απόγνωσης των βουλευτών…
Category: Στίγμα
Author: Γιώργος Παπαχρήστος
Date: Πρώτη Δημοσιεύση:29/04/2026 14:20
--------------------
Headline: Δικαστές
Category: Εμπιστευτικά
Author: Πρετεντέρης Ι.Κ.
Date: Πρώτη Δημοσιεύση:29/04/2026 13:00
--------------------
Headline: Ανδρουλάκης: Πλήττεται ο πυρήνας του κράτους Δικαίου με την αρχειοθέτηση της υπόθεσης των υποκλοπών
Category: Πολιτική
No author found for an article in 'column is-full ro_23'
Date: 29/04/2026 09:33
--------------------
Headline: Υποκλοπές – Πρόεδροι δικηγορικών συλλόγων: H απόφαση του Άρειου Πάγου οδηγεί σε έλλειψη εμπιστοσύνης των πολιτών προς τη Δικαιοσύνη
Category: Δικαιοσύνη
Author: Μίνα Μουστάκα
Date: 28/04/2026 17:45
--------------------
Headline: Ασφάλεια δικαίου
Category: Αγιογραφίες
Author: Μιχάλης Μητσός
Date: Πρώτη Δημοσιεύση:28/04/2026 15:47
--------------------
Headline: ΠΑΣΟΚ: Αρραγές μέτωπο με το βλέμμα στις εκλογές
Category: Πολιτική
Author: Μυρτώ Λιαλιούτη
Date: Πρώτη Δημοσιεύση:28/04/2026 15:30
--------------------
Headline: Σκάνδαλο υποκλοπών: Ο Εισαγγελέας του Αρείου Πάγου δεν είδε νεότερα στοιχεία…
Category: Ελλάδα
Author: Μίνα Μουστάκα
Date: Πρώτη Δημοσιεύση:28/04/2026 14:48
--------------------
Headline: Προβληματισμός
Category: ΚΥΡΙΟ ΑΡΘΡΟ
Author: ΤΑ ΝΕΑ
Date: Πρώτη Δημοσιεύση:28/04/2026 14:00
--------------------
Headline: Κυριάκος Βελόπουλος για την αρχειοθέτηση της υπόθεσης των υποκλοπών: «Είναι ισοπέδωση της δικαιοσύνης»
Category: Πολιτική
No author found for an article in 'column is-full ro_29'
Date: 28/04/2026 10:57
--------------------
Headline: ΠΑΣΟΚ για Γεωργιάδη: «Ποιος μπορεί να πάρει στα σοβαρά αυτόν τον πολιτικό κωλοτούμπα;»
Category: Πολιτική
No author found for an article in 'column is-full ro_30'
Date: 28/04/2026 09:24
--------------------
Headline: Υποκλοπές: Αντιφάσεις στη στάση της κυβέρνησης – Θέλει να αποτρέψει νέα Εξεταστική
Category: Πολιτική
Author: Ελένη Ευαγγελοδήμου
Date: 28/04/2026 06:09
--------------------
Headline: Θετικός για σύσταση Εξεταστικής Επιτροπής για τις υποκλοπές ο ΣΥΡΙΖΑ
Category: Πολιτική
No author found for an article in 'column is-full ro_32'
Date: 27/04/2026 23:24
--------------------
Headline: Υποκλοπές: Συμμαχία για Εξεταστική μετά από τηλεφωνική επικοινωνία Ανδρουλάκη – Φάμελλου – Πέρκα
Category: Πολιτική
Author: Μυρτώ Λαλιούτη
Date: 27/04/2026 22:45
--------------------
Headline: Υποκλοπές: Τι σημαίνει η πρόταση Ανδρουλάκη για Εξεταστική Επιτροπή – Πώς συγκροτείται
Category: Πολιτική
No author found for an article in 'column is-full ro_34'
Date: 27/04/2026 18:53
--------------------
Headline: Απότομη διακοπή της συνέντευξης Ανδρουλάκη για τις υποκλοπές (video)
Category: Ελλάδα
No author found for an article in 'column is-full ro_35'
Date: 27/04/2026 17:49
--------------------
Headline: Ν. Ανδρουλάκης: Θα καταθέσουμε αίτημα για Εξεταστική Επιτροπή – Θα καλέσουμε τον κ. Ντίλιαν στη Βουλή
Category: Πολιτική
No author found for an article in 'column is-full ro_36'
Date: 27/04/2026 17:01
--------------------
--- Processing Page 3 ---
Headline: Υποκλοπές: Θάβεται η υπόθεση στο αρχείο, τι αποφάσισε ο Άρειος Πάγος – Οι αντιδράσεις
Category: Πολιτική
Author: Μίνα Μουστάκα
Date: 27/04/2026 15:43
--------------------
Headline: Τσίπρας: Ό, τι εύκολα μπαίνει στο αρχείο, το ίδιο εύκολα βγαίνει από το αρχείο
Category: Πολιτική
No author found for an article in 'column is-full ro_2'
Date: 27/04/2026 14:16
--------------------
Headline: Μαξίμου για υποκλοπές: Το ΠΑΣΟΚ να πάρει αποστάσεις, «χρειάζεται αυτοσυγκράτηση»
Category: Πολιτική
Author: Ελένη Ευαγγελοδήμου
Date: 27/04/2026 12:24
--------------------
Headline: Υποκλοπές: Ραγδαίες πολιτικές εξελίξεις μετά την απόφαση του Αρείου Πάγου – Έκτακτη συνέντευξη Τύπου Ανδρουλακη
Category: Πολιτική
No author found for an article in 'column is-full ro_4'
Date: 27/04/2026 12:15
--------------------
Headline: Απόφαση με πολιτικές διαστάσεις – Στο αρχείο η υπόθεση των υποκλοπών
Category: Πολιτική
Author: Μίνα Μουστάκα
Date: 27/04/2026 10:44
--------------------
Headline: Άρειος Πάγος: Δεν ανασύρεται από το αρχείο η δικογραφία για τις τηλεφωνικές υποκλοπές
Category: Πολιτική
No author found for an article in 'column is-full ro_6'
Date: 27/04/2026 09:37
--------------------
Headline: ΣΥΡΙΖΑ: H Intellexa παρουσιαζόταν ως «one stop shop» για κρατικές υποκλοπές και «profiling»
Category: Πολιτική
No author found for an article in 'column is-full ro_7'
Date: 25/04/2026 10:20
--------------------
Headline: Υποκλοπές: Η Intellexa του Ντίλιαν, με έδρα την Αθήνα, διαφήμιζε κατασκοπευτικά λογισμικά σε «Αρχές επιβολής του νόμου»
Category: Ελλάδα
No author found for an article in 'column is-full ro_8'
Date: 24/04/2026 12:36
--------------------
Headline: ΠΑΣΟΚ: «Ούτε και τώρα η κυβέρνηση θα βγει να διαψεύσει ευθαρσώς τον κ. Ντίλιαν;»
Category: Πολιτική
Author: TANEA Newsroom
Date: 24/04/2026 11:09
--------------------
Headline: Βουλευτής ΝΔ
Category: Μερική άγνοια
Author: Κώστας Γιαννακίδης
Date: Πρώτη Δημοσιεύση:22/04/2026 14:20
--------------------
Headline: Σεβασμός
Category: ΚΥΡΙΟ ΑΡΘΡΟ
Author: ΤΑ ΝΕΑ
Date: Πρώτη Δημοσιεύση:17/04/2026 14:00
--------------------
Headline: Φάμελλος: Κύριε Μητσοτάκη είστε ένας διαπλεκόμενος και εκβιαζόμενος πρωθυπουργός – Eσείς είστε το βαθύ κράτος
Category: Πολιτική
No author found for an article in 'column is-full ro_12'
Date: 16/04/2026 13:41
--------------------
Headline: Βουλή: Το σκάνδαλο των υποκλοπών στο επίκεντρο της συνεδρίασης
Category: Πολιτική
Author: Μυρτώ Λιαλιούτη
Date: 16/04/2026 07:22
--------------------
Headline: Η Ανάσταση, πέραν του μεταφυσικού
Category: ΕΝ ΟΛΙΓΟΙΣ
Author: Τζίνα Μοσχολιού
Date: Πρώτη Δημοσιεύση:14/04/2026 14:45
--------------------
Headline: Κ. Τσουκαλάς: Οι υποκλοπές και ο ΟΠΕΚΕΠΕ δεν είναι σκάνδαλα του απρόσωπου «βαθέος κράτους», αλλά μιας προσωποπαγούς δομής εξουσίας
Category: Πολιτική
No author found for an article in 'column is-full ro_15'
Date: 14/04/2026 10:06
--------------------
Headline: Υποκλοπές: Πολιτικός σεισμός από την αποκάλυψη των «ΝΕΩΝ» – Μπαράζ παραγραφών φέρνουν οι καθυστερήσεις του Αρείου Πάγου
Category: Πολιτική
No author found for an article in 'column is-full ro_16'
Date: 09/04/2026 20:55
--------------------
Headline: Υποκλοπές: Επιχείρηση παραγραφής – Τα 13 βήµατα στο παρασκήνιο
Category: Ελλάδα
No author found for an article in 'column is-full ro_17'
Date: Πρώτη Δημοσιεύση:09/04/2026 14:30
--------------------
Headline: Υποκλοπές: Στο εδώλιο στις 11 Δεκεμβρίου οι τέσσερις επιχειρηματίες που καταδικάστηκαν
Category: Ελλάδα
Author: Μίνα Μουστάκα
Date: 09/04/2026 12:55
--------------------
Headline: Υποκλοπές: Η δικογραφία «σπάει στα δύο» – Ξεκινούν τέσσερις νέες έρευνες
Category: Ελλάδα
Author: Μίνα Μουστάκα
Date: 07/04/2026 14:47
--------------------
Headline: Μια λύση
Category: ΚΥΡΙΟ ΑΡΘΡΟ
Author: ΤΑ ΝΕΑ
Date: Πρώτη Δημοσιεύση:06/04/2026 14:00
--------------------
Headline: Από τα Τέμπη στις υποκλοπές: Η πολιτική κρίση που βαραίνει την κυβέρνηση
Category: Πολιτική
Author: Τζίνα Μοσχολιού
Date: Πρώτη Δημοσιεύση:05/04/2026 17:35
--------------------
Headline: «Πώς αγοράσατε το Predator;»: Πολιτική θύελλα μετά τις αποκαλύψεις για κρατική χρηματοδότηση της Intellexa
Category: Πολιτική
No author found for an article in 'column is-full ro_22'
Date: 05/04/2026 15:45
--------------------
Headline: Γιατί η ελληνική Φιλελεύθερη Δημοκρατία είναι σε κρίση;
Category: Επισκέπτης
Author: Κωνσταντίνος Σαραβάκος
Date: Πρώτη Δημοσιεύση:03/04/2026 16:20
--------------------
Headline: Αλέξης Τσίπρας: «Ο Κ. Μητσοτάκης να παραιτηθεί όπως ο Νίξον – Η μόνη σχέση του με την Ευρώπη είναι αυτή με την Ευρωπαϊκή Εισαγγελία»
Category: Πολιτική
No author found for an article in 'column is-full ro_24'
Date: 03/04/2026 00:35
--------------------
Headline: Ανδρουλάκης: Εκλογές να τελειώνουμε  – Να μπει τέλος στην ατιμωρησία
Category: Πολιτική
No author found for an article in 'column is-full ro_25'
Date: 02/04/2026 13:47
--------------------
Headline: Ο πήχης
Category: Εν ολίγοις
Author: Τζίνα Μοσχολιού
Date: Πρώτη Δημοσιεύση:01/04/2026 14:50
--------------------
Headline: Μετατίθεται η προ ημερήσιας συζήτηση στη Βουλή για το Κράτος Δικαίου - Θα πραγματοποιηθεί στις 17 Απριλίου, η αντίδραση ΠΑΣΟΚ
Category: Πολιτική
Author: Ελένη Ευαγγελοδήμου
Date: 31/03/2026 15:57
--------------------
Headline: ΠΑΣΟΚ: Τι φοβάται το Μέγαρο Μαξίμου και δεν διαψεύδει τον ιδιοκτήτη της Intellexa;
Category: Πολιτική
No author found for an article in 'column is-full ro_28'
Date: 30/03/2026 14:03
--------------------

In [ ]:
main_content_div = doc.find('div', {'class': 'post-body main-content pos-rel article-wrapper'})

if main_content_div:
    # Find all paragraph tags within the main content div
    paragraphs = main_content_div.find_all('p')
    # Join the text from each paragraph to form the complete article text
    text = '\n'.join([p.get_text(strip=True) for p in paragraphs])
else:
    text = "Main article content div not found."

print(text)

Νέα δεδομένα στηνπολύκροτη υπόθεση των τηλεφωνικών υποκλοπώνσηματοδοτούν οι τελευταίες δηλώσεις του ιδρυτή της ΙντελέξαΤαλ Ντίλιαν, που οδήγησαν τον δημοσιογράφοΘανάση Κουκάκηνα ζητήσει διά του δικηγόρου τουΖαχαρία Κεσσέτην ανάσυρση της δικογραφίας από το αρχείο.
Πριν από λίγη ώρα, ο Ζαχαρίας Κεσσές και ο Θανάσης Κουκάκηςπροσήλθαν στην Εισαγγελία του Αρείου Πάγου και κατέθεσαν αίτηση ανάσυρσης του φακέλου από το αρχείοκαι την εξέταση του καταδικασμένου πρωτοδίκωςΤαλ Ντίλιαν.
Αφορμή αποτέλεσαν οι πρόσφατες δηλώσεις του ιδρυτή της Intellexa στην Εφημερίδα των Συντακτών, ο οποίος ισχυρίστηκε ότι ούτε ο ίδιος, ούτε η εταιρεία του Intellexa λειτούργησαν οι ίδιοι το κατασκοπευτικό λογισμικόPredatorστην Ελλάδα, καθώς και ότι ο μόνος που είχε τη δυνατότητα να το λειτουργήσει ήταν κυβερνήσεις και μυστικές υπηρεσίες, που αποτελούν και τους μοναδικούς πελάτες- αγοραστές της κατασκοπευτικής του τεχνολογίας.
«Πωλούμε σε κρατικές υπηρεσίες σύμφωνα με όλους τους απαιτούμενους κανονισμούς, αλλάποτέ δεν λειτουργούμε τα συστήματα για λογαριασμό τους. Δεν λειτουργήσαμε ποτέ κανένα σύστημα στην Ελλάδα», δήλωσε χαρακτηριστικά ο Ταλ Ντίλιαν.
Σύμφωνα με τα αναφερόμενα στην αίτηση «Δεδομένης της αδιαμφισβήτητης λειτουργίας του κατασκοπευτικού λογισμικού Predator στην Ελλάδα, οι ανωτέρω ισχυρισμοί του Ταλ Ντίλιαν ότι το κατασκοπευτικό λογισμικό Predator χρησιμοποιήθηκε και χρησιμοποιείται αποκλειστικά από κυβερνήσεις και μυστικές υπηρεσίες, οδηγούν στο λογικό συμπέρασμα ότι -κατά τους ισχυρισμούς του- οι εν λόγω παράνομες παρακολουθήσεις πραγματοποιήθηκαν είτε από την ΕΥΠ είτε από ξένη κυβέρνηση ή/και ξένη μυστική υπηρεσία».
Και προστίθεται ότι «ο ισχυρισμός αυτός, ιδωμένος στο πλαίσιο της ήδη διατυπωμένης πεποίθησης της Εισαγγελίας του Αρείου Πάγου ότι η ΕΥΠ δεν εμπλέκεται καθ’ οιονδήποτε τρόπο με τις παράνομες παρακολουθήσεις μέσω Predator, δεν μπορεί να μείνει ανεξέταστος, καθώς τυχόν βασιμότητά του θα σήμαινε κατασκοπευτική δράση τρίτης χώρας στην ελληνική επικράτεια».
Προχωρώντας μάλιστα ένα βήμα παραπέρα προστίθεται πως «τοενδεχόμενο παρακολούθησης ανώτατων πολιτικών και στρατιωτικών αξιωματούχων και ανώτατων στελεχών των μυστικών μας Υπηρεσιών, από ξένες κυβερνήσεις ή ξένες μυστικές υπηρεσίες, θέτει σε ανυπολόγιστο κίνδυνο την εθνική ασφάλεια της χώρας μας. Εξαιτίας αυτού του κινδύνου, η τυχόν μη διερεύνησή της ως άνω δήλωσης, επ’ ουδενί δεν μπορεί να δικαιολογηθεί επί τη βάσει της αμφισβήτησης της αξιοπιστίας του προσώπου που την πραγματοποίησε – ήτοι του Ταλ Ντίλιαν – εκ του γεγονός ότι φέρει την ιδιότητα του κατηγορουμένου».
Υπό αυτό το πρίσμα προβάλλεται «επιβεβλημένη η ουσιαστική διερεύνηση της βασιμότητας των όσων δήλωσε ο  Ταλ Ντίλιαν» προκειμένου να κληθεί ο ίδιος ο πρωταγωνιστής της υπόθεσης να εισφέρει στοιχεία που αποδεικνύουν τους ισχυρισμούς του και αφετέρου καλώντας τον ίδιο και τους λοιπούς συγκατηγορούμενούς του και συμμετέχοντες στην εταιρεία Intellexa (Sara Aleksandra Hamou, Φέλιξ Μπίτζιο και Ιωάννη Λαβράνο) να επιβεβαιώσουν τους ισχυρισμούς του και να εισφέρουν σχετικά αποδεικτικά στοιχεία.
Σε περίπτωση δε που λόγω της ιδιότητας των προαναφερόμενων προσώπων ως κατηγορουμένων θεωρηθούν εξ’ ορισμού ψευδή τα όσα ενδεχομένως εισφέρουν, τότε καθίσταται επιβεβλημένη η κλήτευση συγκεκριμένων προσώπων – στελεχών της εταιρείας Intellexa.
Ειδικότερα, ορισμένα εκ των προσώπων τα οποία σύμφωνα με τα όσα προέκυψαν από τη δικογραφία, διαδραμάτιζαν σημαίνοντα ρόλο στην λειτουργία της εταιρείας Intellexa στην Ελλάδα και δύνανται να εισφέρουν αποδεικτικά των ισχυρισμών του Ταλ Ντίλιαν.
Η εξέταση των προσώπων αυτών που κατονομάζονται ένα προς ένα είναι αναγκαία, όπως επισημαίνει στην αίτηση του οΖαχαρίας Κεσσές, «αφενός για την πλήρη και ουσιαστική διερεύνηση της υπόθεσης και αφετέρου για την προστασία της εθνικής ασφάλειας από τυχόν ανήκεστο βλάβη που θα μπορούσε να προκληθεί σε περίπτωση που ο Tal Dilian αληθώς ισχυρίζεται ότι το Predator χρησιμοποιήθηκε από κυβέρνηση ή μυστική υπηρεσία (ως τους μόνους πελάτες του) και η μυστική αυτή Υπηρεσία δεν ήταν η ΕΥΠ».
«Ζητάμε να κλείσει ένα κενό που εξακολουθεί να διακινδυνεύει την εμπιστοσύνη στην ελληνική δικαιοσύνη και την εθνική ασφάλεια», δήλωσε ο κ. Κεσσές μεταξύ άλλων μετά την κατάθεση της αίτησης.
Αξίζει να σημειωθεί τέλος ότισύμφωνα με πληροφορίες τα θύματα των παρακολουθήσεων ετοιμάζονται να καταθέσουν και τις πρώτες αγωγές αποζημίωσης κατά των ήδη πρωτοδίκως καταδικασθέντων, ενώ εξετάζεται και τοενδεχόμενο προσφυγής στο Ευρωπαϊκό Δικαστήριο Δικαιωμάτων του Ανθρώπουώστε η σοβαρή αυτή υπόθεση να κριθεί και από το Δικαστήριο του Στρασβούργου.

In [7]:
import requests
from bs4 import BeautifulSoup
import pandas as pd # Import pandas
import time

full_articles_data = [] # List to store dictionaries of article data

start_page = 1
end_page = 7
base_tag_url = 'https://www.tanea.gr/tag/%CF%85%CF%80%CE%BF%CE%BA%CE%BB%CE%BF%CF%80%CE%AD%CF%82/'
main_url = 'https://www.tanea.gr'

for page_num in range(start_page, end_page + 1):
    print(f"--- Processing Page {page_num} ---")

    if page_num == 1:
        page_url = base_tag_url
    else:
        page_url = f"{base_tag_url}page/{page_num}/"

    try:
        response_page = requests.get(page_url)
        response_page.raise_for_status() # Raise an HTTPError for bad responses (4xx or 5xx)
        doc = BeautifulSoup(response_page.text, 'html.parser') # Update doc for each page
    except requests.exceptions.RequestException as e:
        print(f"Could not fetch page {page_url}: {e}")
        continue # Skip to the next page if page fetch fails

    article_link_elements = doc.find_all('a', class_='is-block is-relative row-box')

    if not article_link_elements:
        print(f"No article links found on page {page_num}. Skipping.")
        continue

    for article_link_element in article_link_elements:
        story_dict = {} # Dictionary to hold data for the current article
        story_dict['site'] = 'tanea.gr'

        # Get the URL directly from the found link element
        article_href = article_link_element['href']
        if article_href.startswith('http'):
            article_url = article_href
        else:
            article_url = main_url + article_href # Ensure full URL
        story_dict['url'] = article_url

        # The parent div of the link element should be the article teaser container
        article_element = article_link_element.find_parent('div', class_=lambda x: x and 'column is-full' in x)
        if not article_element:
            article_element = article_link_element # Fallback

        headline = article_element.find('h3')
        story_dict['headline'] = headline.text.strip() if headline else ''

        category_element = article_element.find('span', {'class': 'is-bold is-size-4-desktop is-size-5-touch'})
        story_dict['category'] = category_element.text.strip() if category_element else ''

        author_element = article_element.find('span', {'class': 'is-semibold mr-4 uppercase is-size-5 is-neablue mb-1'})
        story_dict['author'] = author_element.text.strip() if author_element else ''

        date_element = article_element.find('span', {'class': 'is-size-5 is-darkblue'})
        story_dict['date'] = date_element.text.strip() if date_element else ''

        # Fetch the full article content
        try:
            response_article = requests.get(article_url)
            response_article.raise_for_status()
            article_doc = BeautifulSoup(response_article.text, 'html.parser')

            main_content_div = article_doc.find('div', {'class': 'post-body main-content pos-rel article-wrapper'})
            if main_content_div:
                paragraphs = main_content_div.find_all('p')
                text = '\n'.join([p.get_text(strip=True) for p in paragraphs if p.get_text(strip=True)])
            else:
                text = "Main article content div not found."
            story_dict['full_text'] = text

        except requests.exceptions.RequestException as e:
            story_dict['full_text'] = f"Error fetching full text: {e}"
        except Exception as e:
            story_dict['full_text'] = f"Error processing full text: {e}"

        full_articles_data.append(story_dict) # Add the story dictionary to the list

    time.sleep(1) # Be respectful to the server

# After the loop, create a Pandas DataFrame
df = pd.DataFrame(full_articles_data)
print("\nFinished scraping. DataFrame head:")
print(df.head())

--- Processing Page 1 ---
--- Processing Page 2 ---
--- Processing Page 3 ---
--- Processing Page 4 ---
--- Processing Page 5 ---
--- Processing Page 6 ---
--- Processing Page 7 ---

Finished scraping. DataFrame head:
       site                                                url  \
0  tanea.gr  https://www.tanea.gr/2026/06/09/politics/tsouk...
1  tanea.gr  https://www.tanea.gr/2026/06/07/politics/ypokl...
2  tanea.gr  https://www.tanea.gr/2026/06/04/politics/maksi...
3  tanea.gr  https://www.tanea.gr/2026/06/04/greece/ypoklop...
4  tanea.gr  https://www.tanea.gr/2026/06/02/politics/ypokl...

                                            headline  category  \
0  Απάντηση Τσουκαλά σε Φλωρίδη: Να ανασυρθεί από...  Πολιτική
1  Υποκλοπές: Νέα πολιτική θύελλα μετά τις αποκαλ...  Πολιτική
2  Μαξίμου για αίτημα ΠΑΣΟΚ να κληθεί στη Βουλή ο...  Πολιτική
3  Υποκλοπές: Ντόμινο εξελίξεων μετά τις δηλώσεις...    Ελλάδα
4  Υποκλοπές: Αίτημα του ΠΑΣΟΚ για ακρόαση στην Ε...  Πολιτική

                author              date  \
0                       09/06/2026 16:39
1                       07/06/2026 16:38
2  Ελένη Ευαγγελοδήμου  04/06/2026 13:20
3        Μίνα Μουστάκα  04/06/2026 12:24
4                       02/06/2026 17:03

                                           full_text
0  Έντονη κριτική στην κυβέρνησημε αφορμή τις δηλ...
1  Έντονους κραδασμούς στο κυβερνητικό στρατόπεδο...
2  Για τηστάση της κυβέρνησης μπροστά στο αίτημα ...
3  Νέα δεδομένα στηνπολύκροτη υπόθεση των τηλεφων...
4  Αίτημαγια ακρόαση τωνΤαλ ΝτίλιανκαιΓρηγόρη Δημ...

In [ ]:
teaser_articles_list = []

start_page = 1
end_page = 7
base_tag_url = 'https://www.tanea.gr/tag/%CF%85%CF%80%CE%BF%CE%BA%CE%BB%CE%BF%CF%80%CE%AD%CF%82/'

for page_num in range(start_page, end_page + 1):
    print(f"--- Processing Page {page_num} ---")

    if page_num == 1:
        page_url = base_tag_url
    else:
        page_url = f"{base_tag_url}page/{page_num}/"

    try:
        response_page = requests.get(page_url)
        response_page.raise_for_status() # Raise an HTTPError for bad responses (4xx or 5xx)
        doc = BeautifulSoup(response_page.text, 'html.parser') # Update doc for each page
    except requests.exceptions.RequestException as e:
        print(f"Could not fetch page {page_url}: {e}")
        continue # Skip to the next page if page fetch fails

    for i in range(1, 37):
        # Construct the class string for the current iteration
        current_class_name = f'column is-full ro_{i}'

        # Find all divs with the constructed class name on the current page's doc
        found_articles_for_i = doc.find_all('div', class_=current_class_name)

        if found_articles_for_i:
            # Add these articles to the main list
            teaser_articles_list.extend(found_articles_for_i)

            # Iterate through the articles found in this specific 'ro_i' class
            # and print their headlines and other details
            for article_element in found_articles_for_i:
                headline = article_element.find('h3')
                if headline:
                    print(f"Headline: {headline.text.strip()}")
                else:
                    print(f"No headline found for an article in '{current_class_name}'")

                # Extract and print category
                category_element = article_element.find('span', {'class': 'is-bold is-size-4-desktop is-size-5-touch'})
                if category_element:
                    print(f"Category: {category_element.text.strip()}")
                else:
                    print(f"No category found for an article in '{current_class_name}'")

                # Extract and print author
                author_element = article_element.find('span', {'class': 'is-semibold mr-4 uppercase is-size-5 is-neablue mb-1'})
                if author_element:
                    print(f"Author: {author_element.text.strip()}")
                else:
                    print(f"No author found for an article in '{current_class_name}'")

                # Extract and print date
                date_element = article_element.find('span', {'class': 'is-size-5 is-darkblue'})
                if date_element:
                    print(f"Date: {date_element.text.strip()}")
                else:
                    print(f"No date found for an article in '{current_class_name}'")
                print("-" * 20) # Separator for clarity between articles
        else:
            print(f"No articles found for class '{current_class_name}' on this page.")
                 #summary_element = article_element.find ('div', {'class': 'post-description is-size-normal is-darkblue text-overflow'} )
                 #if summary_element:
                   #print
            article = doc.find('h2', {'class': 'post-summary m-0 is-medium'}).text
            main_content_div = article.find('div', {'class': 'post-body main-content pos-rel article-wrapper'})
            if main_content_div:
    # Find all paragraph tags within the main content div
              paragraphs = main_content_div.find_all('p')
    # Join the text from each paragraph to form the complete article text
              text = '\n'.join([p.get_text(strip=True) for p in paragraphs])
            else:
              text = "Main article content div not found."
              print(text)

--- Processing Page 1 ---
Headline: Υποκλοπές: Νέα πολιτική θύελλα μετά τις αποκαλύψεις για συμφωνητικό με την ΕΥΠ
Category: Πολιτική
No author found for an article in 'column is-full ro_1'
Date: 07/06/2026 16:38
--------------------
Headline: Μαξίμου για αίτημα ΠΑΣΟΚ να κληθεί στη Βουλή ο Ντίλιαν: «Θα αποφασίσουν τα αρμόδια όργανα»
Category: Πολιτική
Author: Ελένη Ευαγγελοδήμου
Date: 04/06/2026 13:20
--------------------
Headline: Υποκλοπές: Ντόμινο εξελίξεων μετά τις δηλώσεις Ντίλιαν – Ο Κουκάκης ζητά ανάσυρση του φακέλου από το αρχείο
Category: Ελλάδα
Author: Μίνα Μουστάκα
Date: 04/06/2026 12:24
--------------------
Headline: Υποκλοπές: Αίτημα του ΠΑΣΟΚ για ακρόαση στην Επιτροπή Θεσμών και Διαφάνειας των Ταλ Ντίλιαν και Γρηγόρη Δημητριάδη
Category: Πολιτική
No author found for an article in 'column is-full ro_4'
Date: 02/06/2026 17:03
--------------------
Headline: ΕΛΑΣ για δηλώσεις Ντίλιαν: «Ο κ. Μητσοτάκης δεν μπορεί άλλο να κρύβεται – Να δώσει απαντήσεις και στοιχεία»
Category: Πολιτική
Author: TANEA Newsroom
Date: 02/06/2026 11:18
--------------------
Headline: Υποκλοπές: Ντίλιαν καρφώνει κυβέρνηση – «Πουλάμε μόνο σε κρατικές αρχές, δεν λειτουργούμε τα συστήματα οι ίδιοι»
Category: Ελλάδα
No author found for an article in 'column is-full ro_6'
Date: 02/06/2026 10:39
--------------------
Headline: Κ. Τσουκαλάς: Δημοκρατικό καθήκον προς τους πολίτες η διαλεύκανση των παράνομων παρακολουθήσεων
Category: Πολιτική
No author found for an article in 'column is-full ro_7'
Date: 02/06/2026 09:51
--------------------
Headline: Κεσσές για υποκλοπές: Σκυταλοδρομία συγκάλυψης – Προβληματική η ανάθεση της υπόθεσης από τον Τζαβέλλα στον Μπακέλα
Category: Ελλάδα
No author found for an article in 'column is-full ro_8'
Date: 27/05/2026 13:09
--------------------
Headline: Ηρεμα νερά
Category: Απόψεις, Σχόλια & Γνώμες
Author: Παπασπύρος Νίκος
Date: Πρώτη Δημοσιεύση:25/05/2026 18:46
--------------------
Headline: «Ypoklopes Blues»
Category: Απόψεις, Σχόλια & Γνώμες
Author: Γιάννης Φ. Ιωαννίδης
Date: Πρώτη Δημοσιεύση:23/05/2026 18:15
--------------------
Headline: Τσουκαλάς: A λα καρτ αντίληψη της εθνικής ασφάλειας από την κυβέρνηση – Να ζητήσει συγγνώμη από τον Ανδρουλάκη
Category: Πολιτική
No author found for an article in 'column is-full ro_11'
Date: 23/05/2026 13:42
--------------------
Headline: Χάχανο
Category: Μερική άγνοια
Author: Κώστας Γιαννακίδης
Date: Πρώτη Δημοσιεύση:22/05/2026 14:15
--------------------
Headline: Κ. Τσουκαλάς: Ο κ. Φλωρίδης με περισπούδαστο ύφος απηύθυνε ειρωνείες περί “φωστήρων”, αλλά πιάστηκε αδιάβαστος
Category: Πολιτική
No author found for an article in 'column is-full ro_13'
Date: 22/05/2026 13:56
--------------------
Headline: «Βόμβες» Σαμαρά για εθνικά και υποκλοπές: Η Ελλάδα έχει μετατραπεί σε ένα απέραντο φρενοκομείο
Category: Πολιτική
No author found for an article in 'column is-full ro_14'
Date: 22/05/2026 12:23
--------------------
Headline: Υποκλοπές: Καταψηφίστηκε η πρόταση του ΠΑΣΟΚ για σύσταση Εξεταστικής Επιτροπής- «Βόμβες» Σαμαρά
Category: Πολιτική
No author found for an article in 'column is-full ro_15'
Date: 22/05/2026 10:31
--------------------
Headline: Υποκλοπές: Στη Βουλή η κρίσιμη μάχη για την εξεταστική – Το Μαξίμου «δείχνει» εθνική ασφάλεια για την απόρριψη
Category: Πολιτική
No author found for an article in 'column is-full ro_16'
Date: 22/05/2026 09:00
--------------------
Headline: Γκάλοπ
Category: Πίσω από τις κάμερες
Author: Μυρτώ Λιαλιούτη
Date: Πρώτη Δημοσιεύση:21/05/2026 15:07
--------------------
Headline: Υποκλοπές: Τι θα κάνει το Μαξίμου με την Εξεταστική – «Λίγη υπομονή…»
Category: Πολιτική
Author: Ελένη Ευαγγελοδήμου
Date: 21/05/2026 13:16
--------------------
Headline: Ανδρουλάκης κατά Κακλαμάνη για τις υποκλοπές: «Α λα καρτ ευαισθησίες» – Κλιμακώνεται η πολιτική σύγκρουση
Category: Πολιτική
No author found for an article in 'column is-full ro_19'
Date: 20/05/2026 19:49
--------------------
Headline: Υποκλοπές: Στην επιτροπή Δεοντολογίας στέλνει ο Κακλαμάνης το θέμα των διαρροών για ΕΥΠ
Category: Πολιτική
No author found for an article in 'column is-full ro_20'
Date: 20/05/2026 15:55
--------------------
Headline: Δεν είναι αρκετό
Category: Αγιογραφίες
Author: Μιχάλης Μητσός
Date: Πρώτη Δημοσιεύση:20/05/2026 15:17
--------------------
Headline: Κυβερνητικές πηγές για διαρροή διαλόγου Ανδρουλάκη – Δεμίρη: Ο πρόεδρος του ΠΑΣΟΚ μετεξελίσσεται σε «πράσινη Ζωή»
Category: Πολιτική
No author found for an article in 'column is-full ro_22'
Date: 20/05/2026 15:10
--------------------
Headline: Επιτροπή Θεσμών και Διαφάνειας: Αναβλήθηκε η συνεδρίαση για την ακρόαση του Κ. Τζαβέλλα μετά την επιστολή του
Category: Πολιτική
No author found for an article in 'column is-full ro_23'
Date: 20/05/2026 14:32
--------------------
Headline: Υποκλοπές: «Η παρακολούθησή μου διατάχθηκε προφορικά;» – Έντονος διάλογος Ανδρουλάκη-Δεμίρη στην Επιτροπή
Category: Πολιτική
Author: Μυρτώ Λιαλιούτη
Date: 20/05/2026 14:02
--------------------
Headline: Υποκλοπές: Την Παρασκευή η συζήτηση στην ολομέλεια της πρότασης του ΠΑΣΟΚ για εξεταστική επιτροπή
Category: Πολιτική
No author found for an article in 'column is-full ro_25'
Date: 20/05/2026 11:24
--------------------
Headline: Υποκλοπές: Στην Επιτροπή Θεσμών και Διαφάνειας ο Δεμίρης – «Όχι» από Τζαβέλλα
Category: Πολιτική
No author found for an article in 'column is-full ro_26'
Date: 20/05/2026 10:55
--------------------
Headline: Νίκος Ανδρουλάκης: Παρών στην ακρόαση του διοικητή της ΕΥΠ, Θ. Δεμίρη, για τις υποκλοπές
Category: Πολιτική
No author found for an article in 'column is-full ro_27'
Date: 20/05/2026 10:23
--------------------
Headline: Νέα Αριστερά: Ο κ. Τζαβέλλας οφείλει να προσέλθει στην Επιτροπή Θεσμών και Διαφάνειας και να δώσει απαντήσεις
Category: Πολιτική
No author found for an article in 'column is-full ro_28'
Date: 19/05/2026 15:17
--------------------
Headline: ΠΑΣΟΚ για Τζαβέλλα: Η επίκληση της αρχής της διάκρισης των εξουσιών δεν πείθει κανέναν
Category: Πολιτική
No author found for an article in 'column is-full ro_29'
Date: 19/05/2026 15:11
--------------------
Headline: Η Επιτροπή Θεσμών περιμένει αύριο Δεμίρη και Τζαβέλλα
Category: ΜικροΠολιτικός
Author: Ο μικροπολιτικός
Date: Πρώτη Δημοσιεύση:19/05/2026 14:10
--------------------
Headline: «Όχι» Τζαβέλλα στην Επιτροπή Θεσμών για τις υποκλοπές – Επικαλείται διάκριση εξουσιών
Category: Ελλάδα
Author: Μίνα Μουστάκα
Date: 19/05/2026 12:05
--------------------
Headline: Υποκλοπές: Την Τετάρτη στην Eπιτροπή Θεσμών και Διαφάνειας Δεμίρης και Τζαβέλλας
Category: Ελλάδα
No author found for an article in 'column is-full ro_32'
Date: 18/05/2026 16:51
--------------------
Headline: Συνέδριο σε ήρεμα νερά
Category: Στίγμα
Author: Γιώργος Παπαχρήστος
Date: Πρώτη Δημοσιεύση:15/05/2026 14:20
--------------------
Headline: Υποκλοπές: Επανέρχεται ο Χρήστος Σπίρτζης με ερωτήματα για την πορεία της δικογραφίας
Category: Πολιτική
Author: Μίνα Μουστάκα
Date: 14/05/2026 17:44
--------------------
Headline: Σκάνδαλο Υποκλοπών: Έρχονται 6 νέες μηνύσεις που «δείχνουν» κατασκοπεία
Category: Ελλάδα
No author found for an article in 'column is-full ro_35'
Date: 13/05/2026 19:25
--------------------
Headline: «Δεν σχολιάζω κάποιον που είναι ιδιώτης»: Η αμηχανία του Π. Μαρινάκη για τις δηλώσεις του Γρ. Δημητριάδη
Category: Πολιτική
No author found for an article in 'column is-full ro_36'
Date: 11/05/2026 16:40
--------------------
--- Processing Page 2 ---
Headline: Απέφυγε να δώσει απαντήσεις για το σκάνδαλο των υποκλοπών ο Δημητριάδης
Category: Ελλάδα
No author found for an article in 'column is-full ro_1'
Date: 11/05/2026 14:03
--------------------
Headline: Τσουκαλάς: Ελπίζω μετά τον Ντίλιαν που ο πρωθυπουργός μπερδεύει με τον Μπόμπ Ντίλαν, δεν έχει ξεχάσει και τον Δημητριάδη
Category: Πολιτική
No author found for an article in 'column is-full ro_2'
Date: 11/05/2026 10:19
--------------------
Headline: Υποκλοπές: Η παραδοχη ενοχής του Γρηγόρη Δημητριάδη που «δείχνει» προς το Μέγαρο Μαξίμου
Category: Πολιτική
No author found for an article in 'column is-full ro_3'
Date: 10/05/2026 17:55
--------------------
Headline: Στην… πρέσατου ΟΠΕΚΕΠΕ και των υποκλοπών
Category: Ελλάδα
Author: Μίνα Μουστάκα
Date: Πρώτη Δημοσιεύση:10/05/2026 14:25
--------------------
Headline: Βενιζέλος: Αιχμές κατά Τζαβέλλα για τη μη ανάσυρση της δικογραφίας των υποκλοπών από το αρχείο
Category: Πολιτική
No author found for an article in 'column is-full ro_5'
Date: 09/05/2026 21:24
--------------------
Headline: Υποκλοπές: Ανάσυρση της υπόθεσης από το αρχείο και εξαίρεση Τζαβέλλα ζητά ο Σπίρτζης
Category: Πολιτική
Author: Μίνα Μουστάκα
Date: 07/05/2026 13:02
--------------------
Headline: Human Rights Watch: Καταγγέλλει την Κομισιόν για κενά ελέγχου στις εξαγωγές spyware από την ΕΕ
Category: Κόσμος
No author found for an article in 'column is-full ro_7'
Date: 06/05/2026 09:39
--------------------
Headline: Τηλεφωνικές υποκλοπές: Παρέμβαση για την πλήρη διερεύνηση της υπόθεσης έκανε και ο Δικηγορικός Σύλλογος Πειραιά
Category: Ελλάδα
No author found for an article in 'column is-full ro_8'
Date: 05/05/2026 20:31
--------------------
Headline: Οι υποκλοπές ως φαντασία ελέγχου
Category: Απόψεις, Σχόλια & Γνώμες
Author: Λευτέρης Κουσούλης
Date: Πρώτη Δημοσιεύση:05/05/2026 18:31
--------------------
Headline: Μαξίμου: Τεστ συνοχής για… γερά νεύρα – Πώς φτάνει στα «όχι» για Προανακριτική και Εξεταστική
Category: Πολιτική
Author: Ελένη Ευαγγελοδήμου
Date: 05/05/2026 06:22
--------------------
Headline: ΠΑΣΟΚ: Κατατέθηκε η πρόταση σύστασης Eξεταστικής για τις υποκλοπές – Τι περιλαμβάνει
Category: Πολιτική
No author found for an article in 'column is-full ro_11'
Date: 04/05/2026 14:22
--------------------
Headline: Eρευνα
Category: ΚΥΡΙΟ ΑΡΘΡΟ
Author: ΤΑ ΝΕΑ
Date: Πρώτη Δημοσιεύση:04/05/2026 14:00
--------------------
Headline: Ζαχαρίας Κεσσές για υποκλοπές: Ο Τζαβέλλας αποφάσισε συνειδητά να παραβιάσει τον νόμο, είναι ποινικά ελεγκτέος
Category: Ελλάδα
No author found for an article in 'column is-full ro_13'
Date: 02/05/2026 16:57
--------------------
Headline: Σκάνδαλο υποκλοπών: Πολιτική θύελλα για τον ρόλο Τζαβέλλα και τις παρακολουθήσεις της ΕΥΠ
Category: Ελλάδα
No author found for an article in 'column is-full ro_14'
Date: 02/05/2026 16:32
--------------------
Headline: ΣΥΡΙΖΑ – Υποκλοπές: Ο Εισαγγελέας που «αθώωσε» και τον εαυτό του
Category: Πολιτική
No author found for an article in 'column is-full ro_15'
Date: 02/05/2026 14:56
--------------------
Headline: Υποκλοπές: Οι 11 στόχοι του Predator που είχε παρακολουθήσει η ΕΥΠ με υπογραφή Τζαβέλλα
Category: Ελλάδα
No author found for an article in 'column is-full ro_16'
Date: 02/05/2026 14:08
--------------------
Headline: Ένωση Εισαγγελέων για την απόφαση του ΔΣΑ περί παραίτησης Τζαβέλλα – «Τέτοιες ενέργειες πλήττουν το κύρος της Δικαιοσύνης»
Category: Ελλάδα
Author: Μίνα Μουστάκα
Date: 30/04/2026 19:42
--------------------
Headline: Ανδρουλάκης: «Ο κ. Μητσοτάκης είναι επικίνδυνος και πρέπει να παραιτηθεί για να αναπνεύσει η χώρα και η δημοκρατία»
Category: Πολιτική
No author found for an article in 'column is-full ro_18'
Date: 30/04/2026 18:58
--------------------
Headline: Οταν η Κοβέσι ζήτησε να της φέρουν τον Μπακάλη…
Category: ΜικροΠολιτικός
Author: ο μικρο-πολιτικος
Date: Πρώτη Δημοσιεύση:30/04/2026 14:10
--------------------
Headline: Η κραυγή απόγνωσης των βουλευτών…
Category: Στίγμα
Author: Γιώργος Παπαχρήστος
Date: Πρώτη Δημοσιεύση:29/04/2026 14:20
--------------------
Headline: Δικαστές
Category: Εμπιστευτικά
Author: Πρετεντέρης Ι.Κ.
Date: Πρώτη Δημοσιεύση:29/04/2026 13:00
--------------------
Headline: Ανδρουλάκης: Πλήττεται ο πυρήνας του κράτους Δικαίου με την αρχειοθέτηση της υπόθεσης των υποκλοπών
Category: Πολιτική
No author found for an article in 'column is-full ro_22'
Date: 29/04/2026 09:33
--------------------
Headline: Υποκλοπές – Πρόεδροι δικηγορικών συλλόγων: H απόφαση του Άρειου Πάγου οδηγεί σε έλλειψη εμπιστοσύνης των πολιτών προς τη Δικαιοσύνη
Category: Δικαιοσύνη
Author: Μίνα Μουστάκα
Date: 28/04/2026 17:45
--------------------
Headline: Ασφάλεια δικαίου
Category: Αγιογραφίες
Author: Μιχάλης Μητσός
Date: Πρώτη Δημοσιεύση:28/04/2026 15:47
--------------------
Headline: ΠΑΣΟΚ: Αρραγές μέτωπο με το βλέμμα στις εκλογές
Category: Πολιτική
Author: Μυρτώ Λιαλιούτη
Date: Πρώτη Δημοσιεύση:28/04/2026 15:30
--------------------
Headline: Σκάνδαλο υποκλοπών: Ο Εισαγγελέας του Αρείου Πάγου δεν είδε νεότερα στοιχεία…
Category: Ελλάδα
Author: Μίνα Μουστάκα
Date: Πρώτη Δημοσιεύση:28/04/2026 14:48
--------------------
Headline: Προβληματισμός
Category: ΚΥΡΙΟ ΑΡΘΡΟ
Author: ΤΑ ΝΕΑ
Date: Πρώτη Δημοσιεύση:28/04/2026 14:00
--------------------
Headline: Κυριάκος Βελόπουλος για την αρχειοθέτηση της υπόθεσης των υποκλοπών: «Είναι ισοπέδωση της δικαιοσύνης»
Category: Πολιτική
No author found for an article in 'column is-full ro_28'
Date: 28/04/2026 10:57
--------------------
Headline: ΠΑΣΟΚ για Γεωργιάδη: «Ποιος μπορεί να πάρει στα σοβαρά αυτόν τον πολιτικό κωλοτούμπα;»
Category: Πολιτική
No author found for an article in 'column is-full ro_29'
Date: 28/04/2026 09:24
--------------------
Headline: Υποκλοπές: Αντιφάσεις στη στάση της κυβέρνησης – Θέλει να αποτρέψει νέα Εξεταστική
Category: Πολιτική
Author: Ελένη Ευαγγελοδήμου
Date: 28/04/2026 06:09
--------------------
Headline: Θετικός για σύσταση Εξεταστικής Επιτροπής για τις υποκλοπές ο ΣΥΡΙΖΑ
Category: Πολιτική
No author found for an article in 'column is-full ro_31'
Date: 27/04/2026 23:24
--------------------
Headline: Υποκλοπές: Συμμαχία για Εξεταστική μετά από τηλεφωνική επικοινωνία Ανδρουλάκη – Φάμελλου – Πέρκα
Category: Πολιτική
Author: Μυρτώ Λαλιούτη
Date: 27/04/2026 22:45
--------------------
Headline: Υποκλοπές: Τι σημαίνει η πρόταση Ανδρουλάκη για Εξεταστική Επιτροπή – Πώς συγκροτείται
Category: Πολιτική
No author found for an article in 'column is-full ro_33'
Date: 27/04/2026 18:53
--------------------
Headline: Απότομη διακοπή της συνέντευξης Ανδρουλάκη για τις υποκλοπές (video)
Category: Ελλάδα
No author found for an article in 'column is-full ro_34'
Date: 27/04/2026 17:49
--------------------
Headline: Ν. Ανδρουλάκης: Θα καταθέσουμε αίτημα για Εξεταστική Επιτροπή – Θα καλέσουμε τον κ. Ντίλιαν στη Βουλή
Category: Πολιτική
No author found for an article in 'column is-full ro_35'
Date: 27/04/2026 17:01
--------------------
Headline: Υποκλοπές: Θάβεται η υπόθεση στο αρχείο, τι αποφάσισε ο Άρειος Πάγος – Οι αντιδράσεις
Category: Πολιτική
Author: Μίνα Μουστάκα
Date: 27/04/2026 15:43
--------------------
--- Processing Page 3 ---
Headline: Τσίπρας: Ό, τι εύκολα μπαίνει στο αρχείο, το ίδιο εύκολα βγαίνει από το αρχείο
Category: Πολιτική
No author found for an article in 'column is-full ro_1'
Date: 27/04/2026 14:16
--------------------
Headline: Μαξίμου για υποκλοπές: Το ΠΑΣΟΚ να πάρει αποστάσεις, «χρειάζεται αυτοσυγκράτηση»
Category: Πολιτική
Author: Ελένη Ευαγγελοδήμου
Date: 27/04/2026 12:24
--------------------
Headline: Υποκλοπές: Ραγδαίες πολιτικές εξελίξεις μετά την απόφαση του Αρείου Πάγου – Έκτακτη συνέντευξη Τύπου Ανδρουλακη
Category: Πολιτική
No author found for an article in 'column is-full ro_3'
Date: 27/04/2026 12:15
--------------------
Headline: Απόφαση με πολιτικές διαστάσεις – Στο αρχείο η υπόθεση των υποκλοπών
Category: Πολιτική
Author: Μίνα Μουστάκα
Date: 27/04/2026 10:44
--------------------
Headline: Άρειος Πάγος: Δεν ανασύρεται από το αρχείο η δικογραφία για τις τηλεφωνικές υποκλοπές
Category: Πολιτική
No author found for an article in 'column is-full ro_5'
Date: 27/04/2026 09:37
--------------------
Headline: ΣΥΡΙΖΑ: H Intellexa παρουσιαζόταν ως «one stop shop» για κρατικές υποκλοπές και «profiling»
Category: Πολιτική
No author found for an article in 'column is-full ro_6'
Date: 25/04/2026 10:20
--------------------
Headline: Υποκλοπές: Η Intellexa του Ντίλιαν, με έδρα την Αθήνα, διαφήμιζε κατασκοπευτικά λογισμικά σε «Αρχές επιβολής του νόμου»
Category: Ελλάδα
No author found for an article in 'column is-full ro_7'
Date: 24/04/2026 12:36
--------------------
Headline: ΠΑΣΟΚ: «Ούτε και τώρα η κυβέρνηση θα βγει να διαψεύσει ευθαρσώς τον κ. Ντίλιαν;»
Category: Πολιτική
Author: TANEA Newsroom
Date: 24/04/2026 11:09
--------------------
Headline: Βουλευτής ΝΔ
Category: Μερική άγνοια
Author: Κώστας Γιαννακίδης
Date: Πρώτη Δημοσιεύση:22/04/2026 14:20
--------------------
Headline: Σεβασμός
Category: ΚΥΡΙΟ ΑΡΘΡΟ
Author: ΤΑ ΝΕΑ
Date: Πρώτη Δημοσιεύση:17/04/2026 14:00
--------------------
Headline: Φάμελλος: Κύριε Μητσοτάκη είστε ένας διαπλεκόμενος και εκβιαζόμενος πρωθυπουργός – Eσείς είστε το βαθύ κράτος
Category: Πολιτική
No author found for an article in 'column is-full ro_11'
Date: 16/04/2026 13:41
--------------------
Headline: Βουλή: Το σκάνδαλο των υποκλοπών στο επίκεντρο της συνεδρίασης
Category: Πολιτική
Author: Μυρτώ Λιαλιούτη
Date: 16/04/2026 07:22
--------------------
Headline: Η Ανάσταση, πέραν του μεταφυσικού
Category: ΕΝ ΟΛΙΓΟΙΣ
Author: Τζίνα Μοσχολιού
Date: Πρώτη Δημοσιεύση:14/04/2026 14:45
--------------------
Headline: Κ. Τσουκαλάς: Οι υποκλοπές και ο ΟΠΕΚΕΠΕ δεν είναι σκάνδαλα του απρόσωπου «βαθέος κράτους», αλλά μιας προσωποπαγούς δομής εξουσίας
Category: Πολιτική
No author found for an article in 'column is-full ro_14'
Date: 14/04/2026 10:06
--------------------
Headline: Υποκλοπές: Πολιτικός σεισμός από την αποκάλυψη των «ΝΕΩΝ» – Μπαράζ παραγραφών φέρνουν οι καθυστερήσεις του Αρείου Πάγου
Category: Πολιτική
No author found for an article in 'column is-full ro_15'
Date: 09/04/2026 20:55
--------------------
Headline: Υποκλοπές: Επιχείρηση παραγραφής – Τα 13 βήµατα στο παρασκήνιο
Category: Ελλάδα
No author found for an article in 'column is-full ro_16'
Date: Πρώτη Δημοσιεύση:09/04/2026 14:30
--------------------
Headline: Υποκλοπές: Στο εδώλιο στις 11 Δεκεμβρίου οι τέσσερις επιχειρηματίες που καταδικάστηκαν
Category: Ελλάδα
Author: Μίνα Μουστάκα
Date: 09/04/2026 12:55
--------------------
Headline: Υποκλοπές: Η δικογραφία «σπάει στα δύο» – Ξεκινούν τέσσερις νέες έρευνες
Category: Ελλάδα
Author: Μίνα Μουστάκα
Date: 07/04/2026 14:47
--------------------
Headline: Μια λύση
Category: ΚΥΡΙΟ ΑΡΘΡΟ
Author: ΤΑ ΝΕΑ
Date: Πρώτη Δημοσιεύση:06/04/2026 14:00
--------------------
Headline: Από τα Τέμπη στις υποκλοπές: Η πολιτική κρίση που βαραίνει την κυβέρνηση
Category: Πολιτική
Author: Τζίνα Μοσχολιού
Date: Πρώτη Δημοσιεύση:05/04/2026 17:35
--------------------
Headline: «Πώς αγοράσατε το Predator;»: Πολιτική θύελλα μετά τις αποκαλύψεις για κρατική χρηματοδότηση της Intellexa
Category: Πολιτική
No author found for an article in 'column is-full ro_21'
Date: 05/04/2026 15:45
--------------------
Headline: Γιατί η ελληνική Φιλελεύθερη Δημοκρατία είναι σε κρίση;
Category: Επισκέπτης
Author: Κωνσταντίνος Σαραβάκος
Date: Πρώτη Δημοσιεύση:03/04/2026 16:20
--------------------
Headline: Αλέξης Τσίπρας: «Ο Κ. Μητσοτάκης να παραιτηθεί όπως ο Νίξον – Η μόνη σχέση του με την Ευρώπη είναι αυτή με την Ευρωπαϊκή Εισαγγελία»
Category: Πολιτική
No author found for an article in 'column is-full ro_23'
Date: 03/04/2026 00:35
--------------------
Headline: Ανδρουλάκης: Εκλογές να τελειώνουμε  – Να μπει τέλος στην ατιμωρησία
Category: Πολιτική
No author found for an article in 'column is-full ro_24'
Date: 02/04/2026 13:47
--------------------
Headline: Ο πήχης
Category: Εν ολίγοις
Author: Τζίνα Μοσχολιού
Date: Πρώτη Δημοσιεύση:01/04/2026 14:50
--------------------
Headline: Μετατίθεται η προ ημερήσιας συζήτηση στη Βουλή για το Κράτος Δικαίου - Θα πραγματοποιηθεί στις 17 Απριλίου, η αντίδραση ΠΑΣΟΚ
Category: Πολιτική
Author: Ελένη Ευαγγελοδήμου
Date: 31/03/2026 15:57
--------------------
Headline: ΠΑΣΟΚ: Τι φοβάται το Μέγαρο Μαξίμου και δεν διαψεύδει τον ιδιοκτήτη της Intellexa;
Category: Πολιτική
No author found for an article in 'column is-full ro_27'
Date: 30/03/2026 14:03
--------------------
Headline: Η υποκλοπή των θεσμών
Category: Απόψεις, Σχόλια & Γνώμες
Author: Ευάγγελος Βενιζέλος
Date: Πρώτη Δημοσιεύση:29/03/2026 11:30
--------------------

In [ ]:
# The 'df' DataFrame was successfully created in the previous cell 'klm-OTRD9LFw'.
# It contains all the scraped article data.
# Displaying the first 5 rows of the 'df' DataFrame:
print(df.head())

                                                 url  \
0  https://www.tanea.gr/2026/06/07/politics/ypokl...
1  https://www.tanea.gr/2026/06/04/politics/maksi...
2  https://www.tanea.gr/2026/06/04/greece/ypoklop...
3  https://www.tanea.gr/2026/06/02/politics/ypokl...
4  https://www.tanea.gr/2026/06/02/politics/elas-...

                                            headline  category  \
0  Υποκλοπές: Νέα πολιτική θύελλα μετά τις αποκαλ...  Πολιτική
1  Μαξίμου για αίτημα ΠΑΣΟΚ να κληθεί στη Βουλή ο...  Πολιτική
2  Υποκλοπές: Ντόμινο εξελίξεων μετά τις δηλώσεις...    Ελλάδα
3  Υποκλοπές: Αίτημα του ΠΑΣΟΚ για ακρόαση στην Ε...  Πολιτική
4  ΕΛΑΣ για δηλώσεις Ντίλιαν: «Ο κ. Μητσοτάκης δε...  Πολιτική

                author              date  \
0                       07/06/2026 16:38
1  Ελένη Ευαγγελοδήμου  04/06/2026 13:20
2        Μίνα Μουστάκα  04/06/2026 12:24
3                       02/06/2026 17:03
4       TANEA Newsroom  02/06/2026 11:18

                                           full_text
0  Έντονους κραδασμούς στο κυβερνητικό στρατόπεδο...
1  Για τηστάση της κυβέρνησης μπροστά στο αίτημα ...
2  Νέα δεδομένα στηνπολύκροτη υπόθεση των τηλεφων...
3  Αίτημαγια ακρόαση τωνΤαλ ΝτίλιανκαιΓρηγόρη Δημ...
4  ΗΕλληνική Αριστερή ΣυμπαράταξηΕΛ.Α.Σ.εξέδωσε α...

In [ ]:
stories = doc.find_all('div', {'class': 'column is-full'})
for s in stories:
  title = s.find('p', {'class': 'title is-5 medium_title'})
  if title:
    print(title.text)

  # Find the anchor tag within the current story `s`
  link_tag = s.find('a', href=True)

  if link_tag:
    article_href = link_tag['href']
    # Check if the href is already a full URL or needs to be prepended
    if article_href.startswith('http'):
        article_url = article_href
    else:
        article_url = "https://www.tanea.gr" + article_href

    print(article_url)
    article_response = requests.get(article_url)
    article_doc = BeautifulSoup(article_response.text, 'html.parser')

    article_content = article_doc.find_all('p')
    text = " "
    for content in article_content:
      print(content.text)
      text = text + content.text
    div_article = article_doc.find('div', { 'id': 'articleBody' })
    print(div_article)
  else:
    print("Link not found for this story.")

In [11]:
df.to_csv('tanea_articles.csv', index=False, encoding='utf-8-sig')
print('DataFrame saved to tanea_articles.csv')

# Display the first 5 rows of the DataFrame to confirm
display(df.head())

DataFrame saved to tanea_articles.csv

,site,url,headline,category,author,date,full_text
0,tanea.gr,https://www.tanea.gr/2026/06/09/politics/tsouk...,Απάντηση Τσουκαλά σε Φλωρίδη: Να ανασυρθεί από...,Πολιτική,NaN,09/06/2026 16:39,Έντονη κριτική στην κυβέρνησημε αφορμή τις δηλ...
1,tanea.gr,https://www.tanea.gr/2026/06/07/politics/ypokl...,Υποκλοπές: Νέα πολιτική θύελλα μετά τις αποκαλ...,Πολιτική,NaN,07/06/2026 16:38,Έντονους κραδασμούς στο κυβερνητικό στρατόπεδο...
2,tanea.gr,https://www.tanea.gr/2026/06/04/politics/maksi...,Μαξίμου για αίτημα ΠΑΣΟΚ να κληθεί στη Βουλή ο...,Πολιτική,Ελένη Ευαγγελοδήμου,04/06/2026 13:20,Για τηστάση της κυβέρνησης μπροστά στο αίτημα ...
3,tanea.gr,https://www.tanea.gr/2026/06/04/greece/ypoklop...,Υποκλοπές: Ντόμινο εξελίξεων μετά τις δηλώσεις...,Ελλάδα,Μίνα Μουστάκα,04/06/2026 12:24,Νέα δεδομένα στηνπολύκροτη υπόθεση των τηλεφων...
4,tanea.gr,https://www.tanea.gr/2026/06/02/politics/ypokl...,Υποκλοπές: Αίτημα του ΠΑΣΟΚ για ακρόαση στην Ε...,Πολιτική,NaN,02/06/2026 17:03,Αίτημαγια ακρόαση τωνΤαλ ΝτίλιανκαιΓρηγόρη Δημ...

In [12]:
df = pd.read_csv('/content/tanea_articles.csv')
df

,site,url,headline,category,author,date,full_text
0,tanea.gr,https://www.tanea.gr/2026/06/09/politics/tsouk...,Απάντηση Τσουκαλά σε Φλωρίδη: Να ανασυρθεί από...,Πολιτική,NaN,09/06/2026 16:39,Έντονη κριτική στην κυβέρνησημε αφορμή τις δηλ...
1,tanea.gr,https://www.tanea.gr/2026/06/07/politics/ypokl...,Υποκλοπές: Νέα πολιτική θύελλα μετά τις αποκαλ...,Πολιτική,NaN,07/06/2026 16:38,Έντονους κραδασμούς στο κυβερνητικό στρατόπεδο...
2,tanea.gr,https://www.tanea.gr/2026/06/04/politics/maksi...,Μαξίμου για αίτημα ΠΑΣΟΚ να κληθεί στη Βουλή ο...,Πολιτική,Ελένη Ευαγγελοδήμου,04/06/2026 13:20,Για τηστάση της κυβέρνησης μπροστά στο αίτημα ...
3,tanea.gr,https://www.tanea.gr/2026/06/04/greece/ypoklop...,Υποκλοπές: Ντόμινο εξελίξεων μετά τις δηλώσεις...,Ελλάδα,Μίνα Μουστάκα,04/06/2026 12:24,Νέα δεδομένα στηνπολύκροτη υπόθεση των τηλεφων...
4,tanea.gr,https://www.tanea.gr/2026/06/02/politics/ypokl...,Υποκλοπές: Αίτημα του ΠΑΣΟΚ για ακρόαση στην Ε...,Πολιτική,NaN,02/06/2026 17:03,Αίτημαγια ακρόαση τωνΤαλ ΝτίλιανκαιΓρηγόρη Δημ...
...,...,...,...,...,...,...,...
139,tanea.gr,https://www.tanea.gr/2025/02/11/greece/ypoklop...,Υποκλοπές: «Όχι» από Άρειο Πάγο σε Ανδρουλάκη ...,Ελλάδα,Μίνα Μουστάκα,11/02/2025 14:28,Με το σκεπτικό ότι η υπόθεση των τηλεφωνικών υ...
140,tanea.gr,https://www.tanea.gr/2025/01/29/greece/ypoklop...,Υποκλοπές: Στο αρχείο η μήνυση Ανδρουλάκη,Ελλάδα,Μίνα Μουστάκα,29/01/2025 11:12,Στο αρχείο έθεσε ο αντεισαγγελέας του Αρείου Π...
141,tanea.gr,https://www.tanea.gr/2024/11/27/media/sta-nea-...,Στα «ΝΕΑ» της Τετάρτης: Στον εισαγγελέα ο κρεο...,Media,NaN,27/11/2024 01:26,Διαβάστε στα «ΝΕΑ» της Τετάρτης:\nΜήνυση από Α...
142,tanea.gr,https://www.tanea.gr/2024/11/01/politics/omili...,"Ομιλία Αλέξη Τσίπρα με αιχμές για υποκλοπές, Τ...",Πολιτική,NaN,01/11/2024 10:48,Με συγκεκριμένες αιχμές για την κατάσταση στην...
143,tanea.gr,https://www.tanea.gr/2024/09/29/politics/rammo...,Σκάνδαλο υποκλοπών: Πώς εμποδίστηκε ο Ράμμος ν...,Πολιτική,NaN,29/09/2024 18:51,Ο πρόεδρος της Αρχής Διασφάλισης του Απορρήτου...